import { PrismaClient, Role, RiskLevel, ConsentStatus, ReferralPriority, ReferralStatus, DutyStatus, SyncStatus, SosStatus } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding RuralCare database with SIH 26133 domain records...');

  // Default PIN hash for '1234'
  const defaultPinHash = await bcrypt.hash('1234', 10);

  // 1. Clean existing records in reverse dependency order
  await prisma.mockABHAProfile.deleteMany();
  await prisma.mockWorkerDirectory.deleteMany();
  await prisma.mockHPRProfessional.deleteMany();
  await prisma.mockHFRFacility.deleteMany();
  await prisma.emergencyAccessLog.deleteMany();
  await prisma.auditLog.deleteMany();
  await prisma.consentArtifact.deleteMany();
  await prisma.sosAlert.deleteMany();
  await prisma.referral.deleteMany();
  await prisma.aIAssessment.deleteMany();
  await prisma.consultation.deleteMany();
  await prisma.syncRecord.deleteMany();
  await prisma.patient.deleteMany();
  await prisma.worker.deleteMany();
  await prisma.doctor.deleteMany();
  await prisma.facility.deleteMany();
  await prisma.user.deleteMany();

  console.log('✓ Cleaned existing records.');

  // 2. Seed Facilities (ABDM HFR)
  const phcLunkaransar = await prisma.facility.create({
    data: {
      hfrId: 'HFR-2024-00891',
      name: 'PHC Lunkaransar',
      facilityType: 'PHC',
      district: 'Bikaner',
      state: 'Rajasthan',
      latitude: 28.5305,
      longitude: 73.7432,
      address: 'Near Bus Stand, Lunkaransar, Bikaner – 334602',
    },
  });

  const chcBikaner = await prisma.facility.create({
    data: {
      hfrId: 'HFR-2024-00289',
      name: 'CHC Bikaner',
      facilityType: 'CHC',
      district: 'Bikaner',
      state: 'Rajasthan',
      latitude: 28.0229,
      longitude: 73.3119,
      address: 'Station Road, Bikaner – 334001',
    },
  });

  const dhBikaner = await prisma.facility.create({
    data: {
      hfrId: 'HFR-2024-00371',
      name: 'District Hospital Bikaner',
      facilityType: 'DH',
      district: 'Bikaner',
      state: 'Rajasthan',
      latitude: 28.0181,
      longitude: 73.3175,
      address: 'PBM Hospital Campus, Bikaner – 334003',
    },
  });

  // Additional PHCs from ADMIN_STATS / PHC_ACTIVITY
  for (const phc of [
    { name: 'PHC Kolayat', hfrId: 'HFR-2024-00892' },
    { name: 'PHC Nokha', hfrId: 'HFR-2024-00893' },
    { name: 'PHC Deshnok', hfrId: 'HFR-2024-00894' },
    { name: 'PHC Dungargarh', hfrId: 'HFR-2024-00895' },
  ]) {
    await prisma.facility.create({
      data: {
        hfrId: phc.hfrId,
        name: phc.name,
        facilityType: 'PHC',
        district: 'Bikaner',
        state: 'Rajasthan',
      },
    });
  }
  console.log('✓ Seeded facilities.');

  // 3. Seed Users & Profiles

  // Admin: Rajiv Singh
  const adminUser = await prisma.user.create({
    data: {
      phone: '9829000001',
      role: Role.ADMIN,
      fullName: 'Rajiv Singh',
      pinHash: defaultPinHash,
    },
  });

  // Doctor 1: Dr. Ankit Sharma (PHC Lunkaransar)
  const doc1User = await prisma.user.create({
    data: {
      phone: '9829000002',
      role: Role.DOCTOR,
      fullName: 'Dr. Ankit Sharma',
      pinHash: defaultPinHash,
    },
  });
  const doc1 = await prisma.doctor.create({
    data: {
      userId: doc1User.id,
      hprId: 'HPR-2024-00142',
      name: 'Dr. Ankit Sharma',
      specialty: 'General Medicine',
      facilityId: phcLunkaransar.id,
      dutyStatus: DutyStatus.AVAILABLE,
      distance: '2.1 km',
      isPreferred: true,
      recommendationReasons: ['Primary assigned doctor', 'On-duty now', 'General Medicine specialist', 'Nearest PHC'],
    },
  });

  // Doctor 2: Dr. Priya Mehta (CHC Bikaner)
  const doc2User = await prisma.user.create({
    data: {
      phone: '9829000003',
      role: Role.DOCTOR,
      fullName: 'Dr. Priya Mehta',
      pinHash: defaultPinHash,
    },
  });
  const doc2 = await prisma.doctor.create({
    data: {
      userId: doc2User.id,
      hprId: 'HPR-2024-00289',
      name: 'Dr. Priya Mehta',
      specialty: 'Gynaecology & Obstetrics',
      facilityId: chcBikaner.id,
      dutyStatus: DutyStatus.BUSY,
      distance: '8.4 km',
      isPreferred: false,
      recommendationReasons: [],
    },
  });

  // Doctor 3: Dr. Suresh Gupta (District Hospital Bikaner)
  const doc3User = await prisma.user.create({
    data: {
      phone: '9829000004',
      role: Role.DOCTOR,
      fullName: 'Dr. Suresh Gupta',
      pinHash: defaultPinHash,
    },
  });
  const doc3 = await prisma.doctor.create({
    data: {
      userId: doc3User.id,
      hprId: 'HPR-2024-00371',
      name: 'Dr. Suresh Gupta',
      specialty: 'Emergency Medicine',
      facilityId: dhBikaner.id,
      dutyStatus: DutyStatus.AVAILABLE,
      distance: '14.2 km',
      isPreferred: false,
      recommendationReasons: ['Emergency specialist available'],
    },
  });

  // Worker 1: Meena Kumari (ASHA, Govindpur)
  const worker1User = await prisma.user.create({
    data: {
      phone: '9829000005',
      role: Role.WORKER,
      fullName: 'Meena Kumari',
      pinHash: defaultPinHash,
    },
  });
  const worker1 = await prisma.worker.create({
    data: {
      userId: worker1User.id,
      name: 'Meena Kumari',
      workerType: 'ASHA',
      village: 'Govindpur',
      district: 'Bikaner',
      state: 'Rajasthan',
    },
  });

  // Worker 2: Sunita Yadav (ASHA, Khetolai)
  const worker2User = await prisma.user.create({
    data: {
      phone: '9829000006',
      role: Role.WORKER,
      fullName: 'Sunita Yadav',
      pinHash: defaultPinHash,
    },
  });
  const worker2 = await prisma.worker.create({
    data: {
      userId: worker2User.id,
      name: 'Sunita Yadav',
      workerType: 'ASHA',
      village: 'Khetolai',
      district: 'Bikaner',
      state: 'Rajasthan',
    },
  });

  // Worker 3: Raju Singh (Health Worker, Deshnok)
  const worker3User = await prisma.user.create({
    data: {
      phone: '9829000007',
      role: Role.WORKER,
      fullName: 'Raju Singh',
      pinHash: defaultPinHash,
    },
  });
  const worker3 = await prisma.worker.create({
    data: {
      userId: worker3User.id,
      name: 'Raju Singh',
      workerType: 'Health Worker',
      village: 'Deshnok',
      district: 'Bikaner',
      state: 'Rajasthan',
    },
  });
  console.log('✓ Seeded staff & healthcare worker accounts.');

  // 4. Seed Patients

  // Patient 1: Priya Devi
  const pat1User = await prisma.user.create({
    data: {
      phone: '9414158392',
      role: Role.PATIENT,
      fullName: 'Priya Devi',
      pinHash: defaultPinHash,
    },
  });
  const pat1 = await prisma.patient.create({
    data: {
      healthId: 'RHC-2026-8F4K92',
      userId: pat1User.id,
      name: 'Priya Devi',
      nameHi: 'प्रिया देवी',
      age: 28,
      dob: '12 Mar 1998',
      gender: 'F',
      bloodGroup: 'O+',
      phone: '94141 58392',
      village: 'Govindpur',
      district: 'Bikaner',
      state: 'Rajasthan',
      address: 'Ward No. 4, Govindpur, Bikaner, Rajasthan – 334001',
      emergencyContact: { name: 'Rajendra Singh', relation: 'Husband', phone: '98290 17643' },
      allergies: ['Penicillin', 'Sulfa drugs'],
      chronicConditions: ['Anaemia (mild)', 'Hypothyroidism'],
      currentMedications: ['Thyronorm 25 mcg', 'Ferrous Sulphate 200 mg'],
      riskLevel: RiskLevel.MODERATE,
      lastConsultation: '29 Aug 2026',
      healthWorkerId: worker1.id,
      healthWorkerName: 'Meena Kumari (ASHA)',
      registeredAt: '14 Jan 2026',
      consentStatus: ConsentStatus.GRANTED,
      vaccinationStatus: 'Fully vaccinated',
    },
  });

  // Patient 2: Ramesh Kumar
  const pat2User = await prisma.user.create({
    data: {
      phone: '9672944501',
      role: Role.PATIENT,
      fullName: 'Ramesh Kumar',
      pinHash: defaultPinHash,
    },
  });
  const pat2 = await prisma.patient.create({
    data: {
      healthId: 'RHC-2026-3M9P71',
      userId: pat2User.id,
      name: 'Ramesh Kumar',
      nameHi: 'रमेश कुमार',
      age: 45,
      dob: '07 Jun 1981',
      gender: 'M',
      bloodGroup: 'B+',
      phone: '96729 44501',
      village: 'Khetolai',
      district: 'Bikaner',
      state: 'Rajasthan',
      address: 'Near Shiv Temple, Khetolai, Bikaner – 334022',
      emergencyContact: { name: 'Sunita Devi', relation: 'Wife', phone: '98291 30012' },
      allergies: [],
      chronicConditions: ['Type 2 Diabetes', 'Hypertension'],
      currentMedications: ['Metformin 500 mg', 'Amlodipine 5 mg', 'Aspirin 75 mg'],
      riskLevel: RiskLevel.HIGH,
      lastConsultation: '31 Aug 2026',
      healthWorkerId: worker2.id,
      healthWorkerName: 'Sunita Yadav (ASHA)',
      registeredAt: '03 Mar 2026',
      consentStatus: ConsentStatus.GRANTED,
      vaccinationStatus: 'COVID-19 booster due',
    },
  });

  // Patient 3: Sunita Bai
  const pat3User = await prisma.user.create({
    data: {
      phone: '9799928831',
      role: Role.PATIENT,
      fullName: 'Sunita Bai',
      pinHash: defaultPinHash,
    },
  });
  const pat3 = await prisma.patient.create({
    data: {
      healthId: 'RHC-2026-7X2N44',
      userId: pat3User.id,
      name: 'Sunita Bai',
      nameHi: 'सुनीता बाई',
      age: 52,
      dob: '19 Nov 1973',
      gender: 'F',
      bloodGroup: 'A+',
      phone: '97999 28831',
      village: 'Lunkaransar',
      district: 'Bikaner',
      state: 'Rajasthan',
      address: 'Mohalla Baniyon ka, Lunkaransar – 334602',
      emergencyContact: { name: 'Kishore Lal', relation: 'Son', phone: '97990 44120' },
      allergies: ['Aspirin'],
      chronicConditions: [],
      currentMedications: [],
      riskLevel: RiskLevel.LOW,
      lastConsultation: '25 Aug 2026',
      healthWorkerId: worker1.id,
      healthWorkerName: 'Meena Kumari (ASHA)',
      registeredAt: '22 Feb 2026',
      consentStatus: ConsentStatus.GRANTED,
      vaccinationStatus: 'Fully vaccinated',
    },
  });

  // Patient 4: Mohan Lal
  const pat4User = await prisma.user.create({
    data: {
      phone: '9462091004',
      role: Role.PATIENT,
      fullName: 'Mohan Lal',
      pinHash: defaultPinHash,
    },
  });
  const pat4 = await prisma.patient.create({
    data: {
      healthId: 'RHC-2026-2K8Q15',
      userId: pat4User.id,
      name: 'Mohan Lal',
      nameHi: 'मोहन लाल',
      age: 67,
      dob: '02 Apr 1959',
      gender: 'M',
      bloodGroup: 'AB+',
      phone: '94620 91004',
      village: 'Deshnok',
      district: 'Bikaner',
      state: 'Rajasthan',
      address: 'Purana Bazaar, Deshnok, Bikaner – 334801',
      emergencyContact: { name: 'Geeta Devi', relation: 'Daughter', phone: '98288 77601' },
      allergies: ['Ibuprofen', 'Codeine'],
      chronicConditions: ['COPD', 'Hypertension', 'Type 2 Diabetes', 'Chronic Kidney Disease (Stage 2)'],
      currentMedications: ['Tiotropium inhaler', 'Losartan 50 mg', 'Insulin (Mixtard 30)', 'Furosemide 40 mg'],
      riskLevel: RiskLevel.CRITICAL,
      lastConsultation: '31 Aug 2026',
      healthWorkerId: worker3.id,
      healthWorkerName: 'Raju Singh (Health Worker)',
      registeredAt: '08 Jan 2026',
      consentStatus: ConsentStatus.GRANTED,
      vaccinationStatus: 'Influenza vaccine due',
    },
  });

  // Patient 5: Kavita Sharma
  const pat5User = await prisma.user.create({
    data: {
      phone: '9529160772',
      role: Role.PATIENT,
      fullName: 'Kavita Sharma',
      pinHash: defaultPinHash,
    },
  });
  const pat5 = await prisma.patient.create({
    data: {
      healthId: 'RHC-2026-9R6T83',
      userId: pat5User.id,
      name: 'Kavita Sharma',
      nameHi: 'कविता शर्मा',
      age: 34,
      dob: '28 Aug 1992',
      gender: 'F',
      bloodGroup: 'A-',
      phone: '95291 60772',
      village: 'Churi Ajitgarh',
      district: 'Churu',
      state: 'Rajasthan',
      address: 'Ward 7, Churi Ajitgarh, Churu – 331001',
      emergencyContact: { name: 'Ashok Sharma', relation: 'Husband', phone: '98294 50011' },
      allergies: [],
      chronicConditions: [],
      currentMedications: [],
      riskLevel: RiskLevel.LOW,
      lastConsultation: '20 Aug 2026',
      healthWorkerName: 'Poonam Devi (ASHA)',
      registeredAt: '15 May 2026',
      consentStatus: ConsentStatus.GRANTED,
      vaccinationStatus: 'Fully vaccinated',
    },
  });
  console.log('✓ Seeded patients.');

  // 5. Seed Consultations
  const con1 = await prisma.consultation.create({
    data: {
      consultationCode: 'CON-2026-001',
      patientId: pat1.id,
      date: '29 Aug 2026',
      time: '10:15 AM',
      workerId: worker1User.id,
      workerName: 'Meena Kumari',
      doctorId: doc1.id,
      doctorName: 'Dr. Ankit Sharma',
      facilityName: 'PHC Lunkaransar',
      symptoms: ['Fatigue', 'Dizziness', 'Pale skin', 'Shortness of breath'],
      vitals: { temperature: 37.1, bloodPressure: '108/70', heartRate: 92, spo2: 97, weight: 51 },
      diagnosis: 'Moderate Anaemia – likely dietary iron deficiency',
      treatment: 'Iron supplementation increased, dietary counselling',
      prescription: ['Ferrous Sulphate 200 mg (TDS × 3 months)', 'Folic Acid 5 mg (OD × 3 months)', 'Vitamin C 500 mg (OD)'],
      notes: 'Haemoglobin: 8.6 g/dL. Referred for complete blood count at PHC.',
      riskLevel: RiskLevel.MODERATE,
      referralStatus: 'completed',
      followUpDate: '28 Sep 2026',
    },
  });

  const con2 = await prisma.consultation.create({
    data: {
      consultationCode: 'CON-2026-002',
      patientId: pat2.id,
      date: '31 Aug 2026',
      time: '09:40 AM',
      workerId: worker2User.id,
      workerName: 'Sunita Yadav',
      symptoms: ['Chest tightness', 'Sweating', 'Nausea', 'Left arm tingling'],
      vitals: { temperature: 37.4, bloodPressure: '168/102', heartRate: 108, spo2: 94, weight: 79 },
      riskLevel: RiskLevel.CRITICAL,
      referralStatus: 'pending',
    },
  });

  const con3 = await prisma.consultation.create({
    data: {
      consultationCode: 'CON-2026-003',
      patientId: pat4.id,
      date: '31 Aug 2026',
      time: '08:20 AM',
      workerId: worker3User.id,
      workerName: 'Raju Singh',
      symptoms: ['Breathlessness (at rest)', 'Pedal oedema', 'Productive cough', 'Confusion (mild)'],
      vitals: { temperature: 37.8, bloodPressure: '182/110', heartRate: 118, spo2: 88, respiratoryRate: 28 },
      riskLevel: RiskLevel.CRITICAL,
      referralStatus: 'pending',
    },
  });
  console.log('✓ Seeded consultations.');

  // 6. Seed AI Assessments
  await prisma.aIAssessment.create({
    data: {
      assessmentCode: 'AI-2026-001',
      consultationId: con2.id,
      patientId: pat2.id,
      riskLevel: RiskLevel.CRITICAL,
      symptomsConsidered: ['Chest tightness', 'Sweating', 'Nausea', 'Left arm tingling'],
      abnormalVitals: ['BP: 168/102 mmHg (↑↑)', 'Heart Rate: 108 bpm (↑)', 'SpO₂: 94% (↓)'],
      riskFactors: ['Known hypertension', 'Type 2 Diabetes (uncontrolled)', 'Male, 45 years', 'No prior cardiac evaluation'],
      reasoning: 'Patient presents with classic angina-equivalent symptoms in the context of poorly controlled hypertension and diabetes. The combination of chest tightness, left arm tingling, diaphoresis and elevated heart rate raises significant concern for acute coronary syndrome. SpO₂ at 94% with current presentation warrants immediate clinical evaluation.',
      recommendedAction: 'Refer patient IMMEDIATELY to PHC Lunkaransar. Administer aspirin 325 mg if no allergy confirmed. Arrange ambulance/transport urgently. Do not delay referral.',
      confidence: 91,
      generatedAt: '31 Aug 2026, 09:47 AM',
    },
  });

  await prisma.aIAssessment.create({
    data: {
      assessmentCode: 'AI-2026-002',
      consultationId: con3.id,
      patientId: pat4.id,
      riskLevel: RiskLevel.CRITICAL,
      symptomsConsidered: ['Breathlessness at rest', 'Pedal oedema', 'Productive cough', 'Mild confusion'],
      abnormalVitals: ['BP: 182/110 mmHg (↑↑↑)', 'Heart Rate: 118 bpm (↑)', 'SpO₂: 88% (↓↓)', 'Respiratory Rate: 28/min (↑↑)', 'Temperature: 37.8°C (↑)'],
      riskFactors: ['COPD (known)', 'Hypertension Stage 3', 'CKD Stage 2', 'Age 67 years', 'Polypharmacy'],
      reasoning: 'Critically ill patient with acute exacerbation of COPD compounded by possible hypertensive emergency. SpO₂ of 88% indicates severe hypoxaemia. Mild confusion may indicate cerebral hypoperfusion. Immediate oxygen therapy and emergency referral required.',
      recommendedAction: 'EMERGENCY referral to District Hospital Bikaner. Oxygen supplementation (4–6 L/min) if available. Monitor vitals every 5 minutes. Alert receiving facility in advance.',
      confidence: 96,
      generatedAt: '31 Aug 2026, 08:31 AM',
    },
  });
  console.log('✓ Seeded AI assessments.');

  // 7. Seed Referrals
  await prisma.referral.create({
    data: {
      referralCode: 'REF-2026-041',
      patientId: pat2.id,
      patientName: 'Ramesh Kumar',
      fromWorker: 'Sunita Yadav',
      fromWorkerId: worker2User.id,
      toFacilityId: phcLunkaransar.id,
      toPHC: 'PHC Lunkaransar',
      reason: 'Suspected Acute Coronary Syndrome – chest tightness, diaphoresis, elevated BP',
      riskLevel: RiskLevel.CRITICAL,
      status: ReferralStatus.ACCEPTED,
      date: '31 Aug 2026',
      priority: ReferralPriority.EMERGENCY,
      aiSummary: 'AI confidence 91% – ACS presentation. Immediate referral recommended.',
    },
  });

  await prisma.referral.create({
    data: {
      referralCode: 'REF-2026-042',
      patientId: pat4.id,
      patientName: 'Mohan Lal',
      fromWorker: 'Raju Singh',
      fromWorkerId: worker3User.id,
      toFacilityId: dhBikaner.id,
      toPHC: 'District Hospital Bikaner',
      reason: 'Acute COPD exacerbation with hypoxaemia and hypertensive emergency',
      riskLevel: RiskLevel.CRITICAL,
      status: ReferralStatus.IN_CONSULTATION,
      date: '31 Aug 2026',
      priority: ReferralPriority.EMERGENCY,
      aiSummary: 'AI confidence 96% – Critical. Emergency transfer required.',
    },
  });

  await prisma.referral.create({
    data: {
      referralCode: 'REF-2026-038',
      patientId: pat1.id,
      patientName: 'Priya Devi',
      fromWorker: 'Meena Kumari',
      fromWorkerId: worker1User.id,
      toFacilityId: phcLunkaransar.id,
      toPHC: 'PHC Lunkaransar',
      reason: 'Moderate anaemia – requires haematological workup and IV iron evaluation',
      riskLevel: RiskLevel.MODERATE,
      status: ReferralStatus.COMPLETED,
      date: '29 Aug 2026',
      priority: ReferralPriority.ROUTINE,
      aiSummary: 'AI confidence 82% – Moderate anaemia. Dietary + supplementation likely sufficient.',
    },
  });
  console.log('✓ Seeded referrals.');

  // 8. Seed Consents
  await prisma.consentArtifact.createMany({
    data: [
      {
        consentCode: 'CNS-001',
        patientId: pat1.id,
        grantedTo: 'Meena Kumari',
        role: 'ASHA Health Worker',
        organization: 'Village Health Centre, Govindpur',
        status: ConsentStatus.GRANTED,
        purpose: 'Ongoing health monitoring',
        dataScope: ['Vitals', 'Consultations', 'Follow-ups', 'Medications'],
        grantedAt: '14 Jan 2026',
      },
      {
        consentCode: 'CNS-002',
        patientId: pat1.id,
        grantedTo: 'Dr. Ankit Sharma',
        role: 'Doctor',
        organization: 'PHC Lunkaransar',
        facilityId: phcLunkaransar.id,
        status: ConsentStatus.TEMPORARY,
        purpose: 'Clinical consultation & referral',
        dataScope: ['Full Medical History', 'Diagnoses', 'Lab Reports', 'Medications', 'Referrals'],
        grantedAt: '29 Aug 2026',
        expiresAt: '29 Sep 2026',
      },
      {
        consentCode: 'CNS-003',
        patientId: pat1.id,
        grantedTo: 'PHC Lunkaransar Administration',
        role: 'PHC Staff',
        organization: 'PHC Lunkaransar',
        facilityId: phcLunkaransar.id,
        status: ConsentStatus.GRANTED,
        purpose: 'Referral management',
        dataScope: ['Referral Records', 'Contact Information'],
        grantedAt: '14 Jan 2026',
      },
      {
        consentCode: 'CNS-004',
        patientId: pat1.id,
        grantedTo: 'Dr. Priya Mehta',
        role: 'Doctor',
        organization: 'PHC Bikaner',
        facilityId: chcBikaner.id,
        status: ConsentStatus.REVOKED,
        purpose: 'Second opinion',
        dataScope: ['Medical History', 'Lab Reports'],
        grantedAt: '01 Jun 2026',
        expiresAt: '01 Jul 2026',
      },
    ],
  });
  console.log('✓ Seeded consent artifacts.');

  // 9. Seed Audit Logs
  await prisma.auditLog.createMany({
    data: [
      {
        auditCode: 'AUD-001',
        patientId: pat1.id,
        accessorId: doc1User.id,
        accessorName: 'Dr. Ankit Sharma',
        accessorRole: 'Doctor',
        organization: 'PHC Lunkaransar',
        action: 'Viewed medical history & added diagnosis',
        dataAccessed: ['Medical History', 'Diagnoses', 'Lab Reports', 'Medications'],
        timestamp: '31 Aug 2026, 14:32',
        purpose: 'Clinical consultation – referral assessment',
      },
      {
        auditCode: 'AUD-002',
        patientId: pat1.id,
        accessorId: worker1User.id,
        accessorName: 'Meena Kumari',
        accessorRole: 'ASHA Worker',
        organization: 'Village Health Centre, Govindpur',
        action: 'Updated consultation record',
        dataAccessed: ['Vitals', 'Symptoms', 'Consultation Notes'],
        timestamp: '31 Aug 2026, 11:15',
        purpose: 'Routine health assessment',
      },
      {
        auditCode: 'AUD-003',
        patientId: pat1.id,
        accessorId: worker2User.id,
        accessorName: 'Sunita Yadav',
        accessorRole: 'ASHA Worker',
        organization: 'Village Health Centre, Khetolai',
        action: 'Viewed follow-up schedule',
        dataAccessed: ['Follow-up Records'],
        timestamp: '28 Aug 2026, 09:05',
        purpose: 'Follow-up coordination',
      },
      {
        auditCode: 'AUD-004',
        patientId: pat1.id,
        accessorId: doc2User.id,
        accessorName: 'Dr. Priya Mehta',
        accessorRole: 'Doctor',
        organization: 'PHC Bikaner',
        action: 'Viewed patient profile',
        dataAccessed: ['Patient Profile', 'Allergies'],
        timestamp: '15 Aug 2026, 16:48',
        purpose: 'Emergency contact verification',
      },
    ],
  });
  console.log('✓ Seeded audit logs.');

  // 10. Seed Emergency Access Logs (Break-glass)
  await prisma.emergencyAccessLog.createMany({
    data: [
      {
        logCode: 'EAL-2026-001',
        patientId: pat1.id,
        patientHealthId: 'RHC-2026-8F4K92',
        patientName: 'Priya Devi',
        doctorId: doc1.id,
        doctorName: 'Dr. Ankit Sharma',
        facilityId: phcLunkaransar.id,
        facilityName: 'PHC Lunkaransar',
        reason: 'Patient unconscious',
        note: 'Patient found unresponsive, suspected cardiac event, referred by ASHA Sunita Yadav.',
        started: '31 Aug 2026, 14:32',
        ended: '31 Aug 2026, 14:47',
        duration: '15 min',
        records: 'Emergency Medical Summary',
        addlRequested: false,
        status: 'Completed',
      },
      {
        logCode: 'EAL-2026-002',
        patientHealthId: 'TEMP-ER-2026-0046',
        patientName: 'Unknown Patient',
        doctorId: doc2.id,
        doctorName: 'Dr. Priya Mehta',
        facilityId: chcBikaner.id,
        facilityName: 'PHC Bikaner',
        reason: 'Life-threatening condition',
        note: 'RTA victim, unconscious, no ID available. Temp record created.',
        started: '28 Aug 2026, 09:15',
        ended: '28 Aug 2026, 09:30',
        duration: '15 min',
        records: 'Emergency Medical Summary, Vitals',
        addlRequested: true,
        status: 'Completed',
      },
      {
        logCode: 'EAL-2026-003',
        patientId: pat4.id,
        patientHealthId: 'RHC-2026-2K8Q15',
        patientName: 'Mohan Lal',
        doctorId: doc1.id,
        doctorName: 'Dr. Ankit Sharma',
        facilityId: phcLunkaransar.id,
        facilityName: 'PHC Lunkaransar',
        reason: 'Patient unable to provide consent',
        note: 'Acute COPD exacerbation, semi-conscious.',
        started: '31 Aug 2026, 08:35',
        ended: '31 Aug 2026, 08:50',
        duration: '15 min',
        records: 'Emergency Medical Summary, Medications, Allergies',
        addlRequested: true,
        status: 'Completed',
      },
    ],
  });
  console.log('✓ Seeded emergency access logs.');

  // 11. Seed Sync Records
  await prisma.syncRecord.createMany({
    data: [
      { syncCode: 'SYN-001', type: 'Consultation', description: 'Priya Devi – Consultation 29 Aug', status: SyncStatus.SYNCED, recordedAt: '29 Aug 2026, 10:45 AM', syncedAt: '29 Aug 2026, 11:02 AM' },
      { syncCode: 'SYN-002', type: 'Patient Registration', description: 'New patient – Anita Meena', status: SyncStatus.PENDING, recordedAt: '31 Aug 2026, 07:15 AM' },
      { syncCode: 'SYN-003', type: 'Referral', description: 'Ramesh Kumar – Emergency referral', status: SyncStatus.PENDING, recordedAt: '31 Aug 2026, 09:48 AM' },
      { syncCode: 'SYN-004', type: 'Vitals', description: 'Mohan Lal – Vitals record', status: SyncStatus.PENDING, recordedAt: '31 Aug 2026, 08:25 AM' },
      { syncCode: 'SYN-005', type: 'Consultation', description: 'Sunita Bai – Follow-up update', status: SyncStatus.SYNCED, recordedAt: '25 Aug 2026, 02:10 PM', syncedAt: '25 Aug 2026, 02:55 PM' },
      { syncCode: 'SYN-006', type: 'Referral', description: 'Mohan Lal – Emergency referral', status: SyncStatus.FAILED, recordedAt: '31 Aug 2026, 08:32 AM', error: 'Connection timeout after 3 retries' },
      { syncCode: 'SYN-007', type: 'Vitals', description: 'Ramesh Kumar – Vitals record', status: SyncStatus.PENDING, recordedAt: '31 Aug 2026, 09:41 AM' },
    ],
  });
  console.log('✓ Seeded sync records.');

  // 12. Seed Mock ABDM Ecosystem (HFR, HPR, Worker Directory, ABHA Profiles)
  console.log('🏥 Seeding Mock ABDM Ecosystem (Synthetic registry data)...');

  await prisma.mockHFRFacility.createMany({
    data: [
      // Maharashtra Rural Facilities (Tiers: Sub Centre, PHC, CHC, DH, Diagnostic, Telemedicine)
      {
        hfrId: 'HFR-MH-00101',
        facilityName: 'SC Shirwal Pada',
        facilityType: 'Sub Centre',
        subType: 'Ayushman Bharat Health & Wellness Centre',
        ownership: 'Government/Public',
        state: 'Maharashtra',
        district: 'Satara',
        subDistrict: 'Khandala',
        village: 'Shirwal Pada',
        pincode: '412801',
        address: 'Near Gram Panchayat Office, Shirwal Pada, Khandala, Satara – 412801',
        latitude: 18.1342,
        longitude: 73.9854,
        contactPhone: '+91-2169-244101',
        contactEmail: 'sc-shirwal@sbx.ruralcare.gov.in',
        services: ['OPD', 'Maternal & Child Care', 'Immunization', 'First Aid', 'NCD Screening'],
        specialties: ['Community Health', 'Primary Nursing'],
        hasEmergency: false,
        operationalStatus: 'ACTIVE',
        openingHours: '09:00 - 17:00',
        registryStatus: 'VERIFIED_MOCK',
        isMock: true,
      },
      {
        hfrId: 'HFR-MH-00102',
        facilityName: 'SC Velhe Khurd',
        facilityType: 'Sub Centre',
        subType: 'Health & Wellness Sub-Centre',
        ownership: 'Government/Public',
        state: 'Maharashtra',
        district: 'Pune Rural',
        subDistrict: 'Velhe',
        village: 'Velhe Khurd',
        pincode: '412212',
        address: 'Wadi Road, Velhe Khurd, Pune – 412212',
        latitude: 18.2931,
        longitude: 73.6384,
        contactPhone: '+91-2130-221102',
        contactEmail: 'sc-velhe@sbx.ruralcare.gov.in',
        services: ['OPD', 'Maternal Health', 'Immunization', 'Basic Diagnostics'],
        specialties: ['Community Health', 'AYUSH Screening'],
        hasEmergency: false,
        operationalStatus: 'ACTIVE',
        openingHours: '09:00 - 17:00',
        registryStatus: 'VERIFIED_MOCK',
        isMock: true,
      },
      {
        hfrId: 'HFR-MH-00103',
        facilityName: 'PHC Khed Shivapur',
        facilityType: 'PHC',
        subType: 'Primary Health Centre 24x7',
        ownership: 'Government/Public',
        state: 'Maharashtra',
        district: 'Pune Rural',
        subDistrict: 'Haveli',
        village: 'Khed Shivapur',
        pincode: '412205',
        address: 'Old Pune-Bangalore Highway, Khed Shivapur, Haveli, Pune – 412205',
        latitude: 18.3512,
        longitude: 73.8584,
        contactPhone: '+91-20-24380103',
        contactEmail: 'phc-khedshivapur@sbx.ruralcare.gov.in',
        services: ['OPD', '24x7 Emergency', 'IPD (6 Beds)', 'Maternity & Labour Room', 'Laboratory', 'Essential Drugs Dispensary'],
        specialties: ['General Medicine', 'Obstetrics', 'Minor Trauma'],
        hasEmergency: true,
        operationalStatus: 'ACTIVE',
        openingHours: '24x7',
        registryStatus: 'VERIFIED_MOCK',
        isMock: true,
      },
      {
        hfrId: 'HFR-MH-00104',
        facilityName: 'PHC Bhor Dehar',
        facilityType: 'PHC',
        subType: 'Primary Health Centre',
        ownership: 'Government/Public',
        state: 'Maharashtra',
        district: 'Pune Rural',
        subDistrict: 'Bhor',
        village: 'Dehar',
        pincode: '412206',
        address: 'Bhor-Mandhardev Road, Dehar, Bhor, Pune – 412206',
        latitude: 18.1624,
        longitude: 73.8441,
        contactPhone: '+91-2113-230104',
        contactEmail: 'phc-bhor@sbx.ruralcare.gov.in',
        services: ['OPD', 'Maternity Ward', 'Immunization', 'Pharmacy', 'Cold Chain Point'],
        specialties: ['General Medicine', 'Paediatric Care'],
        hasEmergency: false,
        operationalStatus: 'ACTIVE',
        openingHours: '08:00 - 20:00',
        registryStatus: 'VERIFIED_MOCK',
        isMock: true,
      },
      {
        hfrId: 'HFR-MH-00105',
        facilityName: 'PHC Paud Taluka',
        facilityType: 'PHC',
        subType: 'Primary Health Centre 24x7',
        ownership: 'Government/Public',
        state: 'Maharashtra',
        district: 'Pune Rural',
        subDistrict: 'Mulshi',
        village: 'Paud',
        pincode: '412108',
        address: 'Main Road, Near Tahsil Office, Paud, Mulshi, Pune – 412108',
        latitude: 18.5281,
        longitude: 73.6124,
        contactPhone: '+91-20-22920105',
        contactEmail: 'phc-paud@sbx.ruralcare.gov.in',
        services: ['OPD', 'Emergency Stabilisation', 'IPD (10 Beds)', 'Pathology Lab', 'Snakebite Treatment Centre'],
        specialties: ['General Medicine', 'Emergency Medicine'],
        hasEmergency: true,
        operationalStatus: 'ACTIVE',
        openingHours: '24x7',
        registryStatus: 'VERIFIED_MOCK',
        isMock: true,
      },
      {
        hfrId: 'HFR-MH-00201',
        facilityName: 'CHC Saswad Rural',
        facilityType: 'CHC',
        subType: 'Community Health Centre (30 Beds)',
        ownership: 'Government/Public',
        state: 'Maharashtra',
        district: 'Pune Rural',
        subDistrict: 'Purandar',
        village: 'Saswad',
        pincode: '412301',
        address: 'Hadapsar-Saswad Road, Saswad, Purandar, Pune – 412301',
        latitude: 18.3448,
        longitude: 74.0298,
        contactPhone: '+91-2115-222201',
        contactEmail: 'chc-saswad@sbx.ruralcare.gov.in',
        services: ['OPD', 'IPD (30 Beds)', 'Emergency & Trauma Care', 'Operation Theatre', 'Blood Storage', 'Radiology (X-Ray)', 'Sonography'],
        specialties: ['General Surgery', 'Obstetrics & Gynaecology', 'Paediatrics', 'Anaesthesia'],
        hasEmergency: true,
        operationalStatus: 'ACTIVE',
        openingHours: '24x7',
        registryStatus: 'VERIFIED_MOCK',
        isMock: true,
      },
      {
        hfrId: 'HFR-MH-00202',
        facilityName: 'CHC Wai Valley',
        facilityType: 'CHC',
        subType: 'Community Health Centre (50 Beds)',
        ownership: 'Government/Public',
        state: 'Maharashtra',
        district: 'Satara',
        subDistrict: 'Wai',
        village: 'Wai',
        pincode: '412803',
        address: 'Krishna Riverbank Road, Wai, Satara – 412803',
        latitude: 17.9482,
        longitude: 73.8912,
        contactPhone: '+91-2167-282202',
        contactEmail: 'chc-wai@sbx.ruralcare.gov.in',
        services: ['OPD', 'IPD (50 Beds)', 'Emergency Department', 'Surgical Ward', 'High Dependency Unit (HDU)', 'Maternity Wing'],
        specialties: ['General Medicine', 'General Surgery', 'Paediatrics', 'Orthopaedics'],
        hasEmergency: true,
        operationalStatus: 'ACTIVE',
        openingHours: '24x7',
        registryStatus: 'VERIFIED_MOCK',
        isMock: true,
      },
      {
        hfrId: 'HFR-MH-00301',
        facilityName: 'District Hospital Aundh-Pune',
        facilityType: 'District Hospital',
        subType: 'District Hospital (300 Beds)',
        ownership: 'Government/Public',
        state: 'Maharashtra',
        district: 'Pune',
        subDistrict: 'Haveli',
        village: 'Aundh',
        pincode: '411027',
        address: 'Chest Hospital Campus, Aundh, Pune – 411027',
        latitude: 18.5614,
        longitude: 73.8081,
        contactPhone: '+91-20-27280301',
        contactEmail: 'dh-aundh@sbx.ruralcare.gov.in',
        services: ['Tertiary Inpatient Care', 'Comprehensive Emergency Trauma Unit', 'ICU/CCU (24 Beds)', 'Modular OTs', 'Blood Bank', 'CT Scan', 'Dialysis Centre'],
        specialties: ['Cardiology', 'Neurology', 'Orthopaedic Trauma', 'Paediatric ICU', 'General Surgery', 'Emergency Medicine'],
        hasEmergency: true,
        operationalStatus: 'ACTIVE',
        openingHours: '24x7',
        registryStatus: 'VERIFIED_MOCK',
        isMock: true,
      },
      {
        hfrId: 'HFR-MH-00401',
        facilityName: 'Sahyadri Rural Diagnostic & Imaging Centre',
        facilityType: 'Diagnostic Centre',
        subType: 'Public-Private Diagnostic Node',
        ownership: 'Public-Private / Trust',
        state: 'Maharashtra',
        district: 'Pune Rural',
        subDistrict: 'Purandar',
        village: 'Saswad',
        pincode: '412301',
        address: 'Opposite New Bus Stand, Saswad, Pune – 412301',
        latitude: 18.3462,
        longitude: 74.0315,
        contactPhone: '+91-2115-224401',
        contactEmail: 'sahyadri-diag@sbx.ruralcare.gov.in',
        services: ['Digital X-Ray', 'Colour Doppler Sonography', 'Automated Haematology', 'HbA1c & Lipid Panel', 'ECG', 'TMT'],
        specialties: ['Radiodiagnosis', 'Clinical Pathology', 'Biochemistry'],
        hasEmergency: false,
        operationalStatus: 'ACTIVE',
        openingHours: '07:00 - 21:00',
        registryStatus: 'VERIFIED_MOCK',
        isMock: true,
      },
      {
        hfrId: 'HFR-MH-00501',
        facilityName: 'Maharashtra Tele-Consult Hub (eSanjeevani Node)',
        facilityType: 'Telemedicine Node',
        subType: 'State Digital Health Coordination Hub',
        ownership: 'Government/Public',
        state: 'Maharashtra',
        district: 'Pune',
        subDistrict: 'Shivajinagar',
        village: 'Pune City',
        pincode: '411005',
        address: 'Directorate of Health Services Campus, Shivajinagar, Pune – 411005',
        latitude: 18.5308,
        longitude: 73.8474,
        contactPhone: '+91-20-25500501',
        contactEmail: 'telemed-hub@sbx.ruralcare.gov.in',
        services: ['Specialist Tele-consultation', 'Tele-Cardiology / ECG Triaging', 'Tele-Radiology Reporting', 'Virtual Tumor Board / Second Opinion'],
        specialties: ['Tele-Medicine', 'Super-Specialty Guidance'],
        hasEmergency: false,
        operationalStatus: 'ACTIVE',
        openingHours: '08:00 - 20:00',
        registryStatus: 'VERIFIED_MOCK',
        isMock: true,
      },
      // Rajasthan facilities (mapped to Mock HFR to keep existing seed links 100% discoverable)
      {
        hfrId: 'HFR-2024-00891',
        facilityName: 'PHC Lunkaransar',
        facilityType: 'PHC',
        subType: 'Primary Health Centre',
        ownership: 'Government/Public',
        state: 'Rajasthan',
        district: 'Bikaner',
        pincode: '334602',
        address: 'Near Bus Stand, Lunkaransar, Bikaner – 334602',
        latitude: 28.5305,
        longitude: 73.7432,
        contactPhone: '+91-151-2400891',
        contactEmail: 'phc-lunkaransar@sbx.ruralcare.gov.in',
        services: ['OPD', 'Emergency', 'Labour Room', 'Dispensary'],
        specialties: ['General Medicine', 'Maternity'],
        hasEmergency: true,
        operationalStatus: 'ACTIVE',
        openingHours: '24x7',
        registryStatus: 'VERIFIED_MOCK',
        isMock: true,
      },
      {
        hfrId: 'HFR-2024-00289',
        facilityName: 'CHC Bikaner',
        facilityType: 'CHC',
        subType: 'Community Health Centre',
        ownership: 'Government/Public',
        state: 'Rajasthan',
        district: 'Bikaner',
        pincode: '334001',
        address: 'Station Road, Bikaner – 334001',
        latitude: 28.0229,
        longitude: 73.3119,
        contactPhone: '+91-151-2400289',
        contactEmail: 'chc-bikaner@sbx.ruralcare.gov.in',
        services: ['OPD', 'IPD', 'Emergency', 'OT', 'Blood Storage'],
        specialties: ['Gynaecology & Obstetrics', 'Surgery'],
        hasEmergency: true,
        operationalStatus: 'ACTIVE',
        openingHours: '24x7',
        registryStatus: 'VERIFIED_MOCK',
        isMock: true,
      },
      {
        hfrId: 'HFR-2024-00371',
        facilityName: 'District Hospital Bikaner',
        facilityType: 'District Hospital',
        subType: 'District Hospital (PBM Campus)',
        ownership: 'Government/Public',
        state: 'Rajasthan',
        district: 'Bikaner',
        pincode: '334003',
        address: 'PBM Hospital Campus, Bikaner – 334003',
        latitude: 28.0181,
        longitude: 73.3175,
        contactPhone: '+91-151-2400371',
        contactEmail: 'dh-bikaner@sbx.ruralcare.gov.in',
        services: ['Tertiary Inpatient Care', 'ICU', 'Emergency Trauma', 'Blood Bank'],
        specialties: ['Emergency Medicine', 'Cardiology', 'Orthopaedics'],
        hasEmergency: true,
        operationalStatus: 'ACTIVE',
        openingHours: '24x7',
        registryStatus: 'VERIFIED_MOCK',
        isMock: true,
      },
    ],
  });
  console.log('✓ Seeded Mock HFR Facilities (13 facilities across care tiers).');

  // Seed Mock HPR Professionals (12 doctors & specialists across medical councils)
  await prisma.mockHPRProfessional.createMany({
    data: [
      {
        hprId: 'HPR-MH-100201',
        fullName: 'Dr. Nilesh Patil',
        gender: 'Male',
        professionalType: 'Doctor',
        qualification: 'MBBS, MD (General Medicine)',
        specialties: ['General Medicine', 'Infectious Diseases', 'Geriatric Care'],
        registrationNumber: 'MMC-2012-04821',
        registrationCouncil: 'Maharashtra Medical Council',
        state: 'Maharashtra',
        district: 'Pune Rural',
        primaryHfrId: 'HFR-MH-00103',
        primaryFacilityName: 'PHC Khed Shivapur',
        languages: ['Marathi', 'Hindi', 'English'],
        contactPhone: '+91 98220 54321',
        contactEmail: 'nilesh.patil@hpr.sbx',
        verificationStatus: 'VERIFIED_MOCK',
        isMock: true,
      },
      {
        hprId: 'HPR-MH-100202',
        fullName: 'Dr. Sunita Kadam',
        gender: 'Female',
        professionalType: 'Specialist',
        qualification: 'MBBS, MS (Obstetrics & Gynaecology)',
        specialties: ['Obstetrics & Gynaecology', 'High-Risk Pregnancy', 'Reproductive Health'],
        registrationNumber: 'MMC-2015-09182',
        registrationCouncil: 'Maharashtra Medical Council',
        state: 'Maharashtra',
        district: 'Pune Rural',
        primaryHfrId: 'HFR-MH-00201',
        primaryFacilityName: 'CHC Saswad Rural',
        languages: ['Marathi', 'Hindi', 'English'],
        contactPhone: '+91 98220 54322',
        contactEmail: 'sunita.kadam@hpr.sbx',
        verificationStatus: 'VERIFIED_MOCK',
        isMock: true,
      },
      {
        hprId: 'HPR-MH-100203',
        fullName: 'Dr. Rajesh More',
        gender: 'Male',
        professionalType: 'Specialist',
        qualification: 'MBBS, MD (Paediatrics)',
        specialties: ['Paediatrics', 'Neonatology', 'Child Nutrition'],
        registrationNumber: 'MMC-2014-07319',
        registrationCouncil: 'Maharashtra Medical Council',
        state: 'Maharashtra',
        district: 'Pune Rural',
        primaryHfrId: 'HFR-MH-00201',
        primaryFacilityName: 'CHC Saswad Rural',
        languages: ['Marathi', 'Hindi', 'English'],
        contactPhone: '+91 98220 54323',
        contactEmail: 'rajesh.more@hpr.sbx',
        verificationStatus: 'VERIFIED_MOCK',
        isMock: true,
      },
      {
        hprId: 'HPR-MH-100204',
        fullName: 'Dr. Vandana Shinde',
        gender: 'Female',
        professionalType: 'Specialist',
        qualification: 'MBBS, MEM (Emergency Medicine)',
        specialties: ['Emergency Medicine', 'Trauma Resuscitation', 'Critical Care'],
        registrationNumber: 'MMC-2017-11204',
        registrationCouncil: 'Maharashtra Medical Council',
        state: 'Maharashtra',
        district: 'Pune',
        primaryHfrId: 'HFR-MH-00301',
        primaryFacilityName: 'District Hospital Aundh-Pune',
        languages: ['Marathi', 'Hindi', 'English'],
        contactPhone: '+91 98220 54324',
        contactEmail: 'vandana.shinde@hpr.sbx',
        verificationStatus: 'VERIFIED_MOCK',
        isMock: true,
      },
      {
        hprId: 'HPR-MH-100205',
        fullName: 'Dr. Anand Deshmukh',
        gender: 'Male',
        professionalType: 'Specialist',
        qualification: 'MBBS, MS (Orthopaedics)',
        specialties: ['Orthopaedics', 'Spine & Joint Trauma', 'Fracture Care'],
        registrationNumber: 'MMC-2010-03291',
        registrationCouncil: 'Maharashtra Medical Council',
        state: 'Maharashtra',
        district: 'Pune',
        primaryHfrId: 'HFR-MH-00301',
        primaryFacilityName: 'District Hospital Aundh-Pune',
        languages: ['Marathi', 'Hindi', 'English'],
        contactPhone: '+91 98220 54325',
        contactEmail: 'anand.deshmukh@hpr.sbx',
        verificationStatus: 'VERIFIED_MOCK',
        isMock: true,
      },
      {
        hprId: 'HPR-MH-100206',
        fullName: 'Dr. Snehal Joshi',
        gender: 'Female',
        professionalType: 'Specialist',
        qualification: 'MBBS, DMRD (Radiodiagnosis)',
        specialties: ['Radiology & Imaging', 'Ultrasonography', 'Digital Radiography'],
        registrationNumber: 'MMC-2016-08144',
        registrationCouncil: 'Maharashtra Medical Council',
        state: 'Maharashtra',
        district: 'Pune Rural',
        primaryHfrId: 'HFR-MH-00401',
        primaryFacilityName: 'Sahyadri Rural Diagnostic & Imaging Centre',
        languages: ['Marathi', 'Hindi', 'English'],
        contactPhone: '+91 98220 54326',
        contactEmail: 'snehal.joshi@hpr.sbx',
        verificationStatus: 'VERIFIED_MOCK',
        isMock: true,
      },
      {
        hprId: 'HPR-MH-100207',
        fullName: 'Dr. Arvind Kulkarni',
        gender: 'Male',
        professionalType: 'Doctor',
        qualification: 'MBBS, DCH (Child Health)',
        specialties: ['Paediatrics', 'Immunization & Growth Monitoring'],
        registrationNumber: 'MMC-2011-05510',
        registrationCouncil: 'Maharashtra Medical Council',
        state: 'Maharashtra',
        district: 'Pune Rural',
        primaryHfrId: 'HFR-MH-00104',
        primaryFacilityName: 'PHC Bhor Dehar',
        languages: ['Marathi', 'Hindi', 'English'],
        contactPhone: '+91 98220 54327',
        contactEmail: 'arvind.kulkarni@hpr.sbx',
        verificationStatus: 'VERIFIED_MOCK',
        isMock: true,
      },
      {
        hprId: 'HPR-MH-100208',
        fullName: 'Dr. Meenakshi Pawar',
        gender: 'Female',
        professionalType: 'Medical Officer',
        qualification: 'MBBS',
        specialties: ['General Medicine', 'Preventive Healthcare', 'Rural Health'],
        registrationNumber: 'MMC-2019-14280',
        registrationCouncil: 'Maharashtra Medical Council',
        state: 'Maharashtra',
        district: 'Pune Rural',
        primaryHfrId: 'HFR-MH-00105',
        primaryFacilityName: 'PHC Paud Taluka',
        languages: ['Marathi', 'Hindi'],
        contactPhone: '+91 98220 54328',
        contactEmail: 'meenakshi.pawar@hpr.sbx',
        verificationStatus: 'VERIFIED_MOCK',
        isMock: true,
      },
      {
        hprId: 'HPR-MH-100209',
        fullName: 'Dr. Sanjay Bhosale',
        gender: 'Male',
        professionalType: 'Specialist',
        qualification: 'MBBS, MD, DM (Cardiology)',
        specialties: ['Cardiology', 'Tele-ECG Triaging', 'Preventive Cardiology'],
        registrationNumber: 'MMC-2008-01923',
        registrationCouncil: 'Maharashtra Medical Council',
        state: 'Maharashtra',
        district: 'Pune',
        primaryHfrId: 'HFR-MH-00501',
        primaryFacilityName: 'Maharashtra Tele-Consult Hub (eSanjeevani Node)',
        languages: ['Marathi', 'Hindi', 'English'],
        contactPhone: '+91 98220 54329',
        contactEmail: 'sanjay.bhosale@hpr.sbx',
        verificationStatus: 'VERIFIED_MOCK',
        isMock: true,
      },
      {
        hprId: 'HPR-MH-100210',
        fullName: 'Dr. Ananya Thorat',
        gender: 'Female',
        professionalType: 'AYUSH Practitioner',
        qualification: 'BAMS, MD (Ayurveda)',
        specialties: ['Integrative AYUSH Medicine', 'Chronic Lifestyle Disorders'],
        registrationNumber: 'MCIM-2018-06214',
        registrationCouncil: 'Maharashtra Council of Indian Medicine',
        state: 'Maharashtra',
        district: 'Pune Rural',
        primaryHfrId: 'HFR-MH-00102',
        primaryFacilityName: 'SC Velhe Khurd',
        languages: ['Marathi', 'Hindi'],
        contactPhone: '+91 98220 54330',
        contactEmail: 'ananya.thorat@hpr.sbx',
        verificationStatus: 'VERIFIED_MOCK',
        isMock: true,
      },
      // Rajasthan doctors from existing seed
      {
        hprId: 'HPR-2024-00142',
        fullName: 'Dr. Ankit Sharma',
        gender: 'Male',
        professionalType: 'Doctor',
        qualification: 'MBBS, MD (General Medicine)',
        specialties: ['General Medicine'],
        registrationNumber: 'RMC-2016-11029',
        registrationCouncil: 'Rajasthan Medical Council',
        state: 'Rajasthan',
        district: 'Bikaner',
        primaryHfrId: 'HFR-2024-00891',
        primaryFacilityName: 'PHC Lunkaransar',
        languages: ['Hindi', 'English'],
        contactPhone: '+91 98290 00002',
        contactEmail: 'ankit.sharma@hpr.sbx',
        verificationStatus: 'VERIFIED_MOCK',
        isMock: true,
      },
      {
        hprId: 'HPR-2024-00289',
        fullName: 'Dr. Priya Mehta',
        gender: 'Female',
        professionalType: 'Specialist',
        qualification: 'MBBS, MS (Gynaecology & Obstetrics)',
        specialties: ['Gynaecology & Obstetrics'],
        registrationNumber: 'RMC-2018-20491',
        registrationCouncil: 'Rajasthan Medical Council',
        state: 'Rajasthan',
        district: 'Bikaner',
        primaryHfrId: 'HFR-2024-00289',
        primaryFacilityName: 'CHC Bikaner',
        languages: ['Hindi', 'English'],
        contactPhone: '+91 98290 00003',
        contactEmail: 'priya.mehta@hpr.sbx',
        verificationStatus: 'VERIFIED_MOCK',
        isMock: true,
      },
    ],
  });
  console.log('✓ Seeded Mock HPR Professionals (12 verified mock practitioners).');

  // Seed Mock Health Worker Directory (12 ASHA/ANM/CHO operational assignments, distinct from HPR)
  await prisma.mockWorkerDirectory.createMany({
    data: [
      {
        workerCode: 'WRK-MH-ASHA-001',
        name: 'Archana Gaikwad',
        workerType: 'ASHA',
        assignedVillage: 'Shivapur Khurd',
        subCentre: 'SC Velhe Khurd',
        parentPhcName: 'PHC Khed Shivapur',
        parentPhcHfrId: 'HFR-MH-00103',
        district: 'Pune Rural',
        state: 'Maharashtra',
        pincode: '412205',
        contactPhone: '+91 98221 00001',
        languages: ['Marathi', 'Hindi'],
        assignedPopulation: 1150,
        active: true,
        latitude: 18.3551,
        longitude: 73.8612,
      },
      {
        workerCode: 'WRK-MH-ASHA-002',
        name: 'Rekha Jadhav',
        workerType: 'ASHA',
        assignedVillage: 'Kondhanpur',
        subCentre: 'SC Velhe Khurd',
        parentPhcName: 'PHC Khed Shivapur',
        parentPhcHfrId: 'HFR-MH-00103',
        district: 'Pune Rural',
        state: 'Maharashtra',
        pincode: '412205',
        contactPhone: '+91 98221 00002',
        languages: ['Marathi'],
        assignedPopulation: 980,
        active: true,
        latitude: 18.3320,
        longitude: 73.8340,
      },
      {
        workerCode: 'WRK-MH-ASHA-003',
        name: 'Manisha Sawant',
        workerType: 'ASHA',
        assignedVillage: 'Nasrapur',
        subCentre: 'SC Shirwal Pada',
        parentPhcName: 'PHC Bhor Dehar',
        parentPhcHfrId: 'HFR-MH-00104',
        district: 'Pune Rural',
        state: 'Maharashtra',
        pincode: '412206',
        contactPhone: '+91 98221 00003',
        languages: ['Marathi', 'Hindi'],
        assignedPopulation: 1320,
        active: true,
        latitude: 18.1812,
        longitude: 73.8741,
      },
      {
        workerCode: 'WRK-MH-ASHA-004',
        name: 'Kavita Ghadge',
        workerType: 'ASHA',
        assignedVillage: 'Shindewadi',
        subCentre: 'SC Shirwal Pada',
        parentPhcName: 'PHC Bhor Dehar',
        parentPhcHfrId: 'HFR-MH-00104',
        district: 'Satara',
        state: 'Maharashtra',
        pincode: '412801',
        contactPhone: '+91 98221 00004',
        languages: ['Marathi'],
        assignedPopulation: 1040,
        active: true,
        latitude: 18.1410,
        longitude: 73.9720,
      },
      {
        workerCode: 'WRK-MH-ANM-001',
        name: 'Shobha Chavan',
        workerType: 'ANM',
        assignedVillage: 'Khed Shivapur Sector 1',
        subCentre: 'SC Velhe Khurd',
        parentPhcName: 'PHC Khed Shivapur',
        parentPhcHfrId: 'HFR-MH-00103',
        district: 'Pune Rural',
        state: 'Maharashtra',
        pincode: '412205',
        contactPhone: '+91 98221 00005',
        languages: ['Marathi', 'Hindi'],
        assignedPopulation: 4800,
        active: true,
        latitude: 18.3520,
        longitude: 73.8590,
      },
      {
        workerCode: 'WRK-MH-ANM-002',
        name: 'Suman Salunkhe',
        workerType: 'ANM',
        assignedVillage: 'Shirwal Rural',
        subCentre: 'SC Shirwal Pada',
        parentPhcName: 'PHC Bhor Dehar',
        parentPhcHfrId: 'HFR-MH-00104',
        district: 'Satara',
        state: 'Maharashtra',
        pincode: '412801',
        contactPhone: '+91 98221 00006',
        languages: ['Marathi', 'Hindi'],
        assignedPopulation: 5100,
        active: true,
        latitude: 18.1360,
        longitude: 73.9870,
      },
      {
        workerCode: 'WRK-MH-CHO-001',
        name: 'Vikas Kamble',
        workerType: 'CHO',
        assignedVillage: 'Velhe Khurd HW-C',
        subCentre: 'SC Velhe Khurd',
        parentPhcName: 'PHC Khed Shivapur',
        parentPhcHfrId: 'HFR-MH-00103',
        district: 'Pune Rural',
        state: 'Maharashtra',
        pincode: '412212',
        contactPhone: '+91 98221 00007',
        languages: ['Marathi', 'Hindi', 'English'],
        assignedPopulation: 6200,
        active: true,
        latitude: 18.2950,
        longitude: 73.6400,
      },
      {
        workerCode: 'WRK-MH-CHO-002',
        name: 'Poonam Raut',
        workerType: 'CHO',
        assignedVillage: 'Shirwal Pada HW-C',
        subCentre: 'SC Shirwal Pada',
        parentPhcName: 'PHC Bhor Dehar',
        parentPhcHfrId: 'HFR-MH-00104',
        district: 'Satara',
        state: 'Maharashtra',
        pincode: '412801',
        contactPhone: '+91 98221 00008',
        languages: ['Marathi', 'Hindi', 'English'],
        assignedPopulation: 5800,
        active: true,
        latitude: 18.1380,
        longitude: 73.9890,
      },
      {
        workerCode: 'WRK-MH-ASHA-005',
        name: 'Deepali Wagh',
        workerType: 'ASHA',
        assignedVillage: 'Paud Rural',
        subCentre: 'SC Velhe Khurd',
        parentPhcName: 'PHC Paud Taluka',
        parentPhcHfrId: 'HFR-MH-00105',
        district: 'Pune Rural',
        state: 'Maharashtra',
        pincode: '412108',
        contactPhone: '+91 98221 00009',
        languages: ['Marathi'],
        assignedPopulation: 890,
        active: true,
        latitude: 18.5290,
        longitude: 73.6140,
      },
      {
        workerCode: 'WRK-MH-ASHA-006',
        name: 'Ujjwala Jagtap',
        workerType: 'ASHA',
        assignedVillage: 'Saswad Wadi',
        subCentre: 'SC Shirwal Pada',
        parentPhcName: 'CHC Saswad Rural',
        parentPhcHfrId: 'HFR-MH-00201',
        district: 'Pune Rural',
        state: 'Maharashtra',
        pincode: '412301',
        contactPhone: '+91 98221 00010',
        languages: ['Marathi', 'Hindi'],
        assignedPopulation: 1210,
        active: true,
        latitude: 18.3470,
        longitude: 74.0330,
      },
      {
        workerCode: 'WRK-2024-ASHA-01',
        name: 'Meena Kumari',
        workerType: 'ASHA',
        assignedVillage: 'Govindpur',
        subCentre: 'SC Govindpur',
        parentPhcName: 'PHC Lunkaransar',
        parentPhcHfrId: 'HFR-2024-00891',
        district: 'Bikaner',
        state: 'Rajasthan',
        pincode: '334602',
        contactPhone: '+91 98290 00005',
        languages: ['Hindi'],
        assignedPopulation: 1100,
        active: true,
      },
      {
        workerCode: 'WRK-2024-ASHA-02',
        name: 'Sunita Yadav',
        workerType: 'ASHA',
        assignedVillage: 'Khetolai',
        subCentre: 'SC Khetolai',
        parentPhcName: 'PHC Lunkaransar',
        parentPhcHfrId: 'HFR-2024-00891',
        district: 'Bikaner',
        state: 'Rajasthan',
        pincode: '334602',
        contactPhone: '+91 98290 00006',
        languages: ['Hindi'],
        assignedPopulation: 1250,
        active: true,
      },
    ],
  });
  console.log('✓ Seeded Mock Health Worker Directory (12 ASHA/ANM/CHO records).');

  // Seed Mock ABHA Profiles (10 synthetic identities, isMock: true, zero fake Aadhaar)
  await prisma.mockABHAProfile.createMany({
    data: [
      {
        abhaAddress: 'mock-abha-000001@sbx',
        abhaNumber: '91-2345-6789-0001',
        fullName: 'Priya Devi',
        fullNameHi: 'प्रिया देवी',
        gender: 'F',
        dob: '1998-03-12',
        dayOfBirth: '12',
        monthOfBirth: '03',
        yearOfBirth: '1998',
        mobile: '+91 94141 58392',
        address: 'House 42, Ward 3, Govindpur, Lunkaransar, Bikaner – 334602',
        village: 'Govindpur',
        district: 'Bikaner',
        state: 'Rajasthan',
        pincode: '334602',
        authMethods: ['MOBILE_OTP', 'DEMO_AUTH'],
        status: 'ACTIVE',
        isMock: true,
        linkedHealthId: 'RHC-2026-8F4K92',
      },
      {
        abhaAddress: 'mock-abha-000002@sbx',
        abhaNumber: '91-2345-6789-0002',
        fullName: 'Ramesh Kumar',
        fullNameHi: 'रमेश कुमार',
        gender: 'M',
        dob: '1981-11-22',
        dayOfBirth: '22',
        monthOfBirth: '11',
        yearOfBirth: '1981',
        mobile: '+91 98291 23456',
        address: 'Main Basti, Khetolai, Lunkaransar, Bikaner – 334602',
        village: 'Khetolai',
        district: 'Bikaner',
        state: 'Rajasthan',
        pincode: '334602',
        authMethods: ['MOBILE_OTP', 'DEMO_AUTH'],
        status: 'ACTIVE',
        isMock: true,
        linkedHealthId: 'RHC-2026-2M8P14',
      },
      {
        abhaAddress: 'mock-abha-000003@sbx',
        abhaNumber: '91-2345-6789-0003',
        fullName: 'Sunita Bai',
        fullNameHi: 'सुनीता बाई',
        gender: 'F',
        dob: '1991-07-08',
        dayOfBirth: '08',
        monthOfBirth: '07',
        yearOfBirth: '1991',
        mobile: '+91 97845 67890',
        address: 'Ward 7, Deshnok, Bikaner – 334801',
        village: 'Deshnok',
        district: 'Bikaner',
        state: 'Rajasthan',
        pincode: '334801',
        authMethods: ['MOBILE_OTP', 'DEMO_AUTH'],
        status: 'ACTIVE',
        isMock: true,
        linkedHealthId: 'RHC-2026-4N7T31',
      },
      {
        abhaAddress: 'mock-abha-000004@sbx',
        abhaNumber: '91-2345-6789-0004',
        fullName: 'Mohan Lal',
        fullNameHi: 'मोहन लाल',
        gender: 'M',
        dob: '1964-01-15',
        dayOfBirth: '15',
        monthOfBirth: '01',
        yearOfBirth: '1964',
        mobile: '+91 94132 11223',
        address: 'Bikaner Road, Kolayat, Bikaner – 334301',
        village: 'Kolayat',
        district: 'Bikaner',
        state: 'Rajasthan',
        pincode: '334301',
        authMethods: ['MOBILE_OTP', 'DEMO_AUTH'],
        status: 'ACTIVE',
        isMock: true,
        linkedHealthId: 'RHC-2026-6K3W88',
      },
      {
        abhaAddress: 'mock-abha-000005@sbx',
        abhaNumber: '91-2345-6789-0005',
        fullName: 'Anita Meena',
        fullNameHi: 'अनिता मीणा',
        gender: 'F',
        dob: '2002-09-30',
        dayOfBirth: '30',
        monthOfBirth: '09',
        yearOfBirth: '2002',
        mobile: '+91 96024 33445',
        address: 'Railway Colony, Nokha, Bikaner – 334803',
        village: 'Nokha',
        district: 'Bikaner',
        state: 'Rajasthan',
        pincode: '334803',
        authMethods: ['MOBILE_OTP', 'DEMO_AUTH'],
        status: 'ACTIVE',
        isMock: true,
        linkedHealthId: 'RHC-2026-9R1Y55',
      },
      {
        abhaAddress: 'mock-abha-000006@sbx',
        abhaNumber: '91-5510-8291-0006',
        fullName: 'Santosh Jadhav',
        fullNameHi: 'संतोष जाधव',
        gender: 'M',
        dob: '1978-05-14',
        dayOfBirth: '14',
        monthOfBirth: '05',
        yearOfBirth: '1978',
        mobile: '+91 98220 11001',
        address: 'Near Hanuman Temple, Shivapur Khurd, Haveli, Pune – 412205',
        village: 'Shivapur Khurd',
        district: 'Pune Rural',
        state: 'Maharashtra',
        pincode: '412205',
        authMethods: ['MOBILE_OTP', 'DEMO_AUTH'],
        status: 'ACTIVE',
        isMock: true,
      },
      {
        abhaAddress: 'mock-abha-000007@sbx',
        abhaNumber: '91-5510-8291-0007',
        fullName: 'Mangala Gaikwad',
        fullNameHi: 'मंगला गायकवाड',
        gender: 'F',
        dob: '1989-10-04',
        dayOfBirth: '04',
        monthOfBirth: '10',
        yearOfBirth: '1989',
        mobile: '+91 98220 11002',
        address: 'Post Kondhanpur, Haveli, Pune – 412205',
        village: 'Kondhanpur',
        district: 'Pune Rural',
        state: 'Maharashtra',
        pincode: '412205',
        authMethods: ['MOBILE_OTP', 'DEMO_AUTH'],
        status: 'ACTIVE',
        isMock: true,
      },
      {
        abhaAddress: 'mock-abha-000008@sbx',
        abhaNumber: '91-5510-8291-0008',
        fullName: 'Vitthal Shinde',
        fullNameHi: 'विठ्ठल शिंदे',
        gender: 'M',
        dob: '1955-08-20',
        dayOfBirth: '20',
        monthOfBirth: '08',
        yearOfBirth: '1955',
        mobile: '+91 98220 11003',
        address: 'Bazar Peth, Nasrapur, Bhor, Pune – 412206',
        village: 'Nasrapur',
        district: 'Pune Rural',
        state: 'Maharashtra',
        pincode: '412206',
        authMethods: ['MOBILE_OTP', 'DEMO_AUTH'],
        status: 'ACTIVE',
        isMock: true,
      },
      {
        abhaAddress: 'mock-abha-000009@sbx',
        abhaNumber: '91-5510-8291-0009',
        fullName: 'Jayashree Kadam',
        fullNameHi: 'जयश्री कदम',
        gender: 'F',
        dob: '1995-12-18',
        dayOfBirth: '18',
        monthOfBirth: '12',
        yearOfBirth: '1995',
        mobile: '+91 98220 11004',
        address: 'Velhe Khurd, Velhe, Pune – 412212',
        village: 'Velhe Khurd',
        district: 'Pune Rural',
        state: 'Maharashtra',
        pincode: '412212',
        authMethods: ['MOBILE_OTP', 'DEMO_AUTH'],
        status: 'ACTIVE',
        isMock: true,
      },
      {
        abhaAddress: 'mock-abha-000010@sbx',
        abhaNumber: '91-5510-8291-0010',
        fullName: 'Ganesh Chavan',
        fullNameHi: 'गणेश चव्हाण',
        gender: 'M',
        dob: '2000-02-28',
        dayOfBirth: '28',
        monthOfBirth: '02',
        yearOfBirth: '2000',
        mobile: '+91 98220 11005',
        address: 'Shindewadi Phata, Khandala, Satara – 412801',
        village: 'Shindewadi',
        district: 'Satara',
        state: 'Maharashtra',
        pincode: '412801',
        authMethods: ['MOBILE_OTP', 'DEMO_AUTH'],
        status: 'ACTIVE',
        isMock: true,
      },
    ],
  });
  console.log('✓ Seeded Mock ABHA Profiles (10 synthetic patient identities).');

  console.log('🎉 Seeding completed successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Error while seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

