import type { Patient, Consultation, AIAssessment, Referral, AuditEntry, ConsentEntry, SyncRecord, MchRecord, MchDueAlertItem } from './types';

export const PATIENTS: Patient[] = [
  {
    id: 'RHC-2026-8F4K92',
    name: 'Priya Devi',
    nameHi: 'प्रिया देवी',
    age: 28,
    dob: '12 Mar 1998',
    gender: 'F',
    bloodGroup: 'O+',
    phone: '94141 58392',
    village: 'Govindpur',
    district: 'Bikaner',
    state: 'Rajasthan',
    address: 'Ward No. 4, Govindpur, Bikaner, Rajasthan – 334001',
    emergencyContact: { name: 'Rajendra Singh', relation: 'Husband', phone: '98290 17643' },
    allergies: ['Penicillin', 'Sulfa drugs'],
    chronicConditions: ['Anaemia (mild)', 'Hypothyroidism'],
    currentMedications: ['Thyronorm 25 mcg', 'Ferrous Sulphate 200 mg'],
    riskLevel: 'moderate',
    lastConsultation: '29 Aug 2026',
    healthWorker: 'Meena Kumari (ASHA)',
    registeredAt: '14 Jan 2026',
    consentStatus: 'granted',
    vaccinationStatus: 'Fully vaccinated',
  },
  {
    id: 'RHC-2026-3M9P71',
    name: 'Ramesh Kumar',
    nameHi: 'रमेश कुमार',
    age: 45,
    dob: '07 Jun 1981',
    gender: 'M',
    bloodGroup: 'B+',
    phone: '96729 44501',
    village: 'Khetolai',
    district: 'Bikaner',
    state: 'Rajasthan',
    address: 'Near Shiv Temple, Khetolai, Bikaner – 334022',
    emergencyContact: { name: 'Sunita Devi', relation: 'Wife', phone: '98291 30012' },
    allergies: [],
    chronicConditions: ['Type 2 Diabetes', 'Hypertension'],
    currentMedications: ['Metformin 500 mg', 'Amlodipine 5 mg', 'Aspirin 75 mg'],
    riskLevel: 'high',
    lastConsultation: '31 Aug 2026',
    healthWorker: 'Sunita Yadav (ASHA)',
    registeredAt: '03 Mar 2026',
    consentStatus: 'granted',
    vaccinationStatus: 'COVID-19 booster due',
  },
  {
    id: 'RHC-2026-7X2N44',
    name: 'Sunita Bai',
    nameHi: 'सुनीता बाई',
    age: 52,
    dob: '19 Nov 1973',
    gender: 'F',
    bloodGroup: 'A+',
    phone: '97999 28831',
    village: 'Lunkaransar',
    district: 'Bikaner',
    state: 'Rajasthan',
    address: 'Mohalla Baniyon ka, Lunkaransar – 334602',
    emergencyContact: { name: 'Kishore Lal', relation: 'Son', phone: '97990 44120' },
    allergies: ['Aspirin'],
    chronicConditions: [],
    currentMedications: [],
    riskLevel: 'low',
    lastConsultation: '25 Aug 2026',
    healthWorker: 'Meena Kumari (ASHA)',
    registeredAt: '22 Feb 2026',
    consentStatus: 'granted',
    vaccinationStatus: 'Fully vaccinated',
  },
  {
    id: 'RHC-2026-2K8Q15',
    name: 'Mohan Lal',
    nameHi: 'मोहन लाल',
    age: 67,
    dob: '02 Apr 1959',
    gender: 'M',
    bloodGroup: 'AB+',
    phone: '94620 91004',
    village: 'Deshnok',
    district: 'Bikaner',
    state: 'Rajasthan',
    address: 'Purana Bazaar, Deshnok, Bikaner – 334801',
    emergencyContact: { name: 'Geeta Devi', relation: 'Daughter', phone: '98288 77601' },
    allergies: ['Ibuprofen', 'Codeine'],
    chronicConditions: ['COPD', 'Hypertension', 'Type 2 Diabetes', 'Chronic Kidney Disease (Stage 2)'],
    currentMedications: ['Tiotropium inhaler', 'Losartan 50 mg', 'Insulin (Mixtard 30)', 'Furosemide 40 mg'],
    riskLevel: 'critical',
    lastConsultation: '31 Aug 2026',
    healthWorker: 'Raju Singh (Health Worker)',
    registeredAt: '08 Jan 2026',
    consentStatus: 'granted',
    vaccinationStatus: 'Influenza vaccine due',
  },
  {
    id: 'RHC-2026-9R6T83',
    name: 'Kavita Sharma',
    nameHi: 'कविता शर्मा',
    age: 34,
    dob: '28 Aug 1992',
    gender: 'F',
    bloodGroup: 'A-',
    phone: '95291 60772',
    village: 'Churi Ajitgarh',
    district: 'Churu',
    state: 'Rajasthan',
    address: 'Ward 7, Churi Ajitgarh, Churu – 331001',
    emergencyContact: { name: 'Ashok Sharma', relation: 'Husband', phone: '98294 50011' },
    allergies: [],
    chronicConditions: [],
    currentMedications: [],
    riskLevel: 'low',
    lastConsultation: '20 Aug 2026',
    healthWorker: 'Poonam Devi (ASHA)',
    registeredAt: '15 May 2026',
    consentStatus: 'granted',
    vaccinationStatus: 'Fully vaccinated',
  },
];

export const CONSULTATIONS: Consultation[] = [
  {
    id: 'CON-2026-001',
    patientId: 'RHC-2026-8F4K92',
    date: '29 Aug 2026',
    time: '10:15 AM',
    workerName: 'Meena Kumari',
    doctorName: 'Dr. Ankit Sharma',
    symptoms: ['Fatigue', 'Dizziness', 'Pale skin', 'Shortness of breath'],
    vitals: { temperature: 37.1, bloodPressure: '108/70', heartRate: 92, spo2: 97, weight: 51 },
    diagnosis: 'Moderate Anaemia – likely dietary iron deficiency',
    treatment: 'Iron supplementation increased, dietary counselling',
    prescription: ['Ferrous Sulphate 200 mg (TDS × 3 months)', 'Folic Acid 5 mg (OD × 3 months)', 'Vitamin C 500 mg (OD)'],
    notes: 'Haemoglobin: 8.6 g/dL. Referred for complete blood count at PHC.',
    riskLevel: 'moderate',
    referralStatus: 'completed',
    followUpDate: '28 Sep 2026',
  },
  {
    id: 'CON-2026-002',
    patientId: 'RHC-2026-3M9P71',
    date: '31 Aug 2026',
    time: '09:40 AM',
    workerName: 'Sunita Yadav',
    symptoms: ['Chest tightness', 'Sweating', 'Nausea', 'Left arm tingling'],
    vitals: { temperature: 37.4, bloodPressure: '168/102', heartRate: 108, spo2: 94, weight: 79 },
    riskLevel: 'critical',
    referralStatus: 'pending',
  },
  {
    id: 'CON-2026-003',
    patientId: 'RHC-2026-2K8Q15',
    date: '31 Aug 2026',
    time: '08:20 AM',
    workerName: 'Raju Singh',
    symptoms: ['Breathlessness (at rest)', 'Pedal oedema', 'Productive cough', 'Confusion (mild)'],
    vitals: { temperature: 37.8, bloodPressure: '182/110', heartRate: 118, spo2: 88, respiratoryRate: 28 },
    riskLevel: 'critical',
    referralStatus: 'pending',
  },
];

export const AI_ASSESSMENTS: AIAssessment[] = [
  {
    id: 'AI-2026-001',
    consultationId: 'CON-2026-002',
    patientId: 'RHC-2026-3M9P71',
    riskLevel: 'critical',
    symptomsConsidered: ['Chest tightness', 'Sweating', 'Nausea', 'Left arm tingling'],
    abnormalVitals: ['BP: 168/102 mmHg (↑↑)', 'Heart Rate: 108 bpm (↑)', 'SpO₂: 94% (↓)'],
    riskFactors: ['Known hypertension', 'Type 2 Diabetes (uncontrolled)', 'Male, 45 years', 'No prior cardiac evaluation'],
    reasoning: 'Patient presents with classic angina-equivalent symptoms in the context of poorly controlled hypertension and diabetes. The combination of chest tightness, left arm tingling, diaphoresis and elevated heart rate raises significant concern for acute coronary syndrome. SpO₂ at 94% with current presentation warrants immediate clinical evaluation.',
    recommendedAction: 'Refer patient IMMEDIATELY to PHC Lunkaransar. Administer aspirin 325 mg if no allergy confirmed. Arrange ambulance/transport urgently. Do not delay referral.',
    confidence: 91,
    generatedAt: '31 Aug 2026, 09:47 AM',
  },
  {
    id: 'AI-2026-002',
    consultationId: 'CON-2026-003',
    patientId: 'RHC-2026-2K8Q15',
    riskLevel: 'critical',
    symptomsConsidered: ['Breathlessness at rest', 'Pedal oedema', 'Productive cough', 'Mild confusion'],
    abnormalVitals: ['BP: 182/110 mmHg (↑↑↑)', 'Heart Rate: 118 bpm (↑)', 'SpO₂: 88% (↓↓)', 'Respiratory Rate: 28/min (↑↑)', 'Temperature: 37.8°C (↑)'],
    riskFactors: ['COPD (known)', 'Hypertension Stage 3', 'CKD Stage 2', 'Age 67 years', 'Polypharmacy'],
    reasoning: 'Critically ill patient with acute exacerbation of COPD compounded by possible hypertensive emergency. SpO₂ of 88% indicates severe hypoxaemia. Mild confusion may indicate cerebral hypoperfusion. Immediate oxygen therapy and emergency referral required.',
    recommendedAction: 'EMERGENCY referral to District Hospital Bikaner. Oxygen supplementation (4–6 L/min) if available. Monitor vitals every 5 minutes. Alert receiving facility in advance.',
    confidence: 96,
    generatedAt: '31 Aug 2026, 08:31 AM',
  },
];

export const REFERRALS: Referral[] = [
  {
    id: 'REF-2026-041',
    patientId: 'RHC-2026-3M9P71',
    patientName: 'Ramesh Kumar',
    fromWorker: 'Sunita Yadav',
    toPHC: 'PHC Lunkaransar',
    reason: 'Suspected Acute Coronary Syndrome – chest tightness, diaphoresis, elevated BP',
    riskLevel: 'critical',
    status: 'accepted',
    date: '31 Aug 2026',
    priority: 'emergency',
    aiSummary: 'AI confidence 91% – ACS presentation. Immediate referral recommended.',
  },
  {
    id: 'REF-2026-042',
    patientId: 'RHC-2026-2K8Q15',
    patientName: 'Mohan Lal',
    fromWorker: 'Raju Singh',
    toPHC: 'District Hospital Bikaner',
    reason: 'Acute COPD exacerbation with hypoxaemia and hypertensive emergency',
    riskLevel: 'critical',
    status: 'in-consultation',
    date: '31 Aug 2026',
    priority: 'emergency',
    aiSummary: 'AI confidence 96% – Critical. Emergency transfer required.',
  },
  {
    id: 'REF-2026-038',
    patientId: 'RHC-2026-8F4K92',
    patientName: 'Priya Devi',
    fromWorker: 'Meena Kumari',
    toPHC: 'PHC Lunkaransar',
    reason: 'Moderate anaemia – requires haematological workup and IV iron evaluation',
    riskLevel: 'moderate',
    status: 'completed',
    date: '29 Aug 2026',
    priority: 'routine',
    aiSummary: 'AI confidence 82% – Moderate anaemia. Dietary + supplementation likely sufficient.',
  },
];

export const AUDIT_LOG: AuditEntry[] = [
  {
    id: 'AUD-001',
    patientId: 'RHC-2026-8F4K92',
    accessorName: 'Dr. Ankit Sharma',
    accessorRole: 'Doctor',
    organization: 'PHC Lunkaransar',
    action: 'Viewed medical history & added diagnosis',
    dataAccessed: ['Medical History', 'Diagnoses', 'Lab Reports', 'Medications'],
    timestamp: '31 Aug 2026, 14:32',
    purpose: 'Clinical consultation – referral assessment',
  },
  {
    id: 'AUD-002',
    patientId: 'RHC-2026-8F4K92',
    accessorName: 'Meena Kumari',
    accessorRole: 'ASHA Worker',
    organization: 'Village Health Centre, Govindpur',
    action: 'Updated consultation record',
    dataAccessed: ['Vitals', 'Symptoms', 'Consultation Notes'],
    timestamp: '31 Aug 2026, 11:15',
    purpose: 'Routine health assessment',
  },
  {
    id: 'AUD-003',
    patientId: 'RHC-2026-8F4K92',
    accessorName: 'Sunita Yadav',
    accessorRole: 'ASHA Worker',
    organization: 'Village Health Centre, Khetolai',
    action: 'Viewed follow-up schedule',
    dataAccessed: ['Follow-up Records'],
    timestamp: '28 Aug 2026, 09:05',
    purpose: 'Follow-up coordination',
  },
  {
    id: 'AUD-004',
    patientId: 'RHC-2026-8F4K92',
    accessorName: 'Dr. Priya Mehta',
    accessorRole: 'Doctor',
    organization: 'PHC Bikaner',
    action: 'Viewed patient profile',
    dataAccessed: ['Patient Profile', 'Allergies'],
    timestamp: '15 Aug 2026, 16:48',
    purpose: 'Emergency contact verification',
  },
];

export const CONSENT_ENTRIES: ConsentEntry[] = [
  {
    id: 'CNS-001',
    grantedTo: 'Meena Kumari',
    role: 'ASHA Health Worker',
    organization: 'Village Health Centre, Govindpur',
    status: 'granted',
    purpose: 'Ongoing health monitoring',
    dataScope: ['Vitals', 'Consultations', 'Follow-ups', 'Medications'],
    grantedAt: '14 Jan 2026',
  },
  {
    id: 'CNS-002',
    grantedTo: 'Dr. Ankit Sharma',
    role: 'Doctor',
    organization: 'PHC Lunkaransar',
    status: 'temporary',
    purpose: 'Clinical consultation & referral',
    dataScope: ['Full Medical History', 'Diagnoses', 'Lab Reports', 'Medications', 'Referrals'],
    grantedAt: '29 Aug 2026',
    expiresAt: '29 Sep 2026',
  },
  {
    id: 'CNS-003',
    grantedTo: 'PHC Lunkaransar Administration',
    role: 'PHC Staff',
    organization: 'PHC Lunkaransar',
    status: 'granted',
    purpose: 'Referral management',
    dataScope: ['Referral Records', 'Contact Information'],
    grantedAt: '14 Jan 2026',
  },
  {
    id: 'CNS-004',
    grantedTo: 'Dr. Priya Mehta',
    role: 'Doctor',
    organization: 'PHC Bikaner',
    status: 'revoked',
    purpose: 'Second opinion',
    dataScope: ['Medical History', 'Lab Reports'],
    grantedAt: '01 Jun 2026',
    expiresAt: '01 Jul 2026',
  },
];

export const SYNC_RECORDS: SyncRecord[] = [
  { id: 'SYN-001', type: 'Consultation', description: 'Priya Devi – Consultation 29 Aug', status: 'synced', recordedAt: '29 Aug 2026, 10:45 AM', syncedAt: '29 Aug 2026, 11:02 AM' },
  { id: 'SYN-002', type: 'Patient Registration', description: 'New patient – Anita Meena', status: 'pending', recordedAt: '31 Aug 2026, 07:15 AM' },
  { id: 'SYN-003', type: 'Referral', description: 'Ramesh Kumar – Emergency referral', status: 'pending', recordedAt: '31 Aug 2026, 09:48 AM' },
  { id: 'SYN-004', type: 'Vitals', description: 'Mohan Lal – Vitals record', status: 'pending', recordedAt: '31 Aug 2026, 08:25 AM' },
  { id: 'SYN-005', type: 'Consultation', description: 'Sunita Bai – Follow-up update', status: 'synced', recordedAt: '25 Aug 2026, 02:10 PM', syncedAt: '25 Aug 2026, 02:55 PM' },
  { id: 'SYN-006', type: 'Referral', description: 'Mohan Lal – Emergency referral', status: 'failed', recordedAt: '31 Aug 2026, 08:32 AM', error: 'Connection timeout after 3 retries' },
  { id: 'SYN-007', type: 'Vitals', description: 'Ramesh Kumar – Vitals record', status: 'pending', recordedAt: '31 Aug 2026, 09:41 AM' },
];

export const ADMIN_STATS = {
  totalPatients: 3847,
  activeWorkers: 52,
  totalConsultations: 1284,
  referralsThisMonth: 118,
  highRiskCases: 23,
  pendingFollowUps: 67,
  syncSuccess: 98.2,
  villagesCovered: 89,
};

export const DISEASE_TRENDS = [
  { condition: 'Anaemia', count: 312, pct: 72 },
  { condition: 'Hypertension', count: 248, pct: 58 },
  { condition: 'Diabetes', count: 187, pct: 43 },
  { condition: 'Malnutrition', count: 143, pct: 33 },
  { condition: 'Respiratory Infections', count: 134, pct: 31 },
  { condition: 'Dengue / Malaria', count: 89, pct: 21 },
];

export const PHC_ACTIVITY = [
  { phc: 'PHC Lunkaransar', consultations: 342, referrals: 28, workers: 14 },
  { phc: 'PHC Kolayat', consultations: 287, referrals: 22, workers: 11 },
  { phc: 'PHC Nokha', consultations: 219, referrals: 18, workers: 9 },
  { phc: 'PHC Deshnok', consultations: 198, referrals: 14, workers: 8 },
  { phc: 'PHC Dungargarh', consultations: 238, referrals: 36, workers: 10 },
];

export const MCH_RECORDS: MchRecord[] = [
  {
    id: 'mch-001',
    patientId: 'RHC-2026-8F4K92',
    patientName: 'Priya Devi',
    patientHealthId: 'RHC-2026-8F4K92',
    patientPhone: '94141 58392',
    patientVillage: 'Govindpur',
    pregnancyStatus: 'PREGNANT',
    edd: '15 Nov 2026',
    lmp: '08 Feb 2026',
    gestationalWeeks: 26,
    isHighRisk: true,
    hrpIndicators: ['Severe Anaemia (Hb 8.6 g/dL)', 'Hypothyroidism'],
    gravida: 1,
    para: 0,
    bloodGroup: 'O+',
    assignedVillage: 'Govindpur',
    assignedWorkerName: 'Meena Kumari (ASHA)',
    nextScheduledDate: '22 Sep 2026',
    nextScheduledMilestone: 'ANC Checkup 3 & IFA 2nd Allotment',
    notes: '26 weeks along. High-risk moderate anaemia. Monitor Hb & blood pressure closely.',
    milestones: [
      {
        id: 'm1-anc1',
        code: 'ANC-1',
        name: 'Antenatal Checkup 1 (Registration)',
        category: 'maternal',
        recommendedWeekOrAge: '12th week',
        dueDate: '14 Mar 2026',
        completedDate: '14 Mar 2026',
        status: 'completed',
        administeredBy: 'Meena Kumari (ASHA)',
        facilityName: 'PHC Lunkaransar',
        batchNumber: 'REG-2026-081',
        notes: 'Pregnancy confirmed. Baseline blood tests, Hb: 8.9 g/dL.',
        vitals: { bloodPressure: '110/70', weight: 49, haemoglobin: 8.9 },
      },
      {
        id: 'm1-tt1',
        code: 'TT-1',
        name: 'Tetanus Toxoid 1 / Td-1',
        category: 'maternal',
        recommendedWeekOrAge: 'Early pregnancy',
        dueDate: '14 Mar 2026',
        completedDate: '14 Mar 2026',
        status: 'completed',
        administeredBy: 'Staff Nurse Sunita',
        facilityName: 'PHC Lunkaransar',
        batchNumber: 'TT-2025-992',
      },
      {
        id: 'm1-ifa1',
        code: 'IFA-1',
        name: 'IFA 1st Allotment (100 Tablets)',
        category: 'maternal',
        recommendedWeekOrAge: 'From 14th week',
        dueDate: '14 Mar 2026',
        completedDate: '14 Mar 2026',
        status: 'completed',
        administeredBy: 'Meena Kumari (ASHA)',
        facilityName: 'Govindpur Sub-Centre',
        notes: '100 tablets of Iron & Folic Acid distributed with compliance instructions.',
      },
      {
        id: 'm1-anc2',
        code: 'ANC-2',
        name: 'Antenatal Checkup 2 (14–26 Weeks)',
        category: 'maternal',
        recommendedWeekOrAge: '20th week',
        dueDate: '12 May 2026',
        completedDate: '12 May 2026',
        status: 'completed',
        administeredBy: 'Dr. Ankit Sharma',
        facilityName: 'PHC Lunkaransar',
        notes: 'Fundal height 20 cm. Fetal heart sound audible (142 bpm). Hb: 8.6 g/dL.',
        vitals: { bloodPressure: '108/70', weight: 51, haemoglobin: 8.6, fetalHeartRate: '142 bpm' },
      },
      {
        id: 'm1-tt2',
        code: 'TT-2',
        name: 'Tetanus Toxoid 2 / Td-2 Booster',
        category: 'maternal',
        recommendedWeekOrAge: '4 weeks after TT-1',
        dueDate: '12 May 2026',
        completedDate: '12 May 2026',
        status: 'completed',
        administeredBy: 'Staff Nurse Sunita',
        facilityName: 'PHC Lunkaransar',
        batchNumber: 'TT-2026-104',
      },
      {
        id: 'm1-anc3',
        code: 'ANC-3',
        name: 'Antenatal Checkup 3 (28–34 Weeks)',
        category: 'maternal',
        recommendedWeekOrAge: '28th week',
        dueDate: '22 Sep 2026',
        status: 'due',
        notes: 'High-risk follow-up for severe anaemia & fetal growth assessment at Village Health & Nutrition Day (VHND).',
      },
      {
        id: 'm1-ifa2',
        code: 'IFA-2',
        name: 'IFA 2nd Allotment (80 Tablets)',
        category: 'maternal',
        recommendedWeekOrAge: '28th week',
        dueDate: '22 Sep 2026',
        status: 'due',
        notes: '2nd round distribution of IFA tablets for third trimester.',
      },
      {
        id: 'm1-anc4',
        code: 'ANC-4',
        name: 'Antenatal Checkup 4 (36 Weeks to Delivery)',
        category: 'maternal',
        recommendedWeekOrAge: '36th week',
        dueDate: '24 Oct 2026',
        status: 'upcoming',
        notes: 'Pre-delivery birth planning, institutional delivery confirmation at CHC Bikaner.',
      },
    ],
  },
  {
    id: 'mch-002',
    patientId: 'pat-sunita-aarav',
    patientName: 'Sunita Kumari & Baby Aarav',
    patientHealthId: 'RHC-2026-SK8801',
    patientPhone: '94142 88120',
    patientVillage: 'Govindpur',
    pregnancyStatus: 'POSTPARTUM',
    childName: 'Baby Aarav',
    childDob: '05 Aug 2026',
    childGender: 'Male',
    childAgeWeeks: 6,
    isHighRisk: true,
    hrpIndicators: ['Low Birth Weight (2.1 kg)'],
    assignedVillage: 'Govindpur',
    assignedWorkerName: 'Meena Kumari (ASHA)',
    nextScheduledDate: '18 Sep 2026',
    nextScheduledMilestone: 'Pentavalent-1 + OPV-1 + Rotavirus-1',
    notes: 'Born at 37 weeks. Birth weight 2.1 kg. Kangaroo Mother Care given. Now 3.2 kg.',
    milestones: [
      {
        id: 'm2-bcg',
        code: 'BCG',
        name: 'BCG Vaccine (Birth Dose)',
        category: 'child',
        recommendedWeekOrAge: 'At Birth',
        dueDate: '05 Aug 2026',
        completedDate: '06 Aug 2026',
        status: 'completed',
        administeredBy: 'Auxiliary Nurse Midwife (ANM)',
        facilityName: 'PHC Lunkaransar',
        batchNumber: 'BCG-2026-551',
      },
      {
        id: 'm2-opv0',
        code: 'OPV-0',
        name: 'Oral Polio Vaccine (OPV Birth Dose)',
        category: 'child',
        recommendedWeekOrAge: 'At Birth (within 14 days)',
        dueDate: '05 Aug 2026',
        completedDate: '06 Aug 2026',
        status: 'completed',
        administeredBy: 'ANM Saroj',
        facilityName: 'PHC Lunkaransar',
        batchNumber: 'OPV-2026-302',
      },
      {
        id: 'm2-penta1',
        code: 'PENTAVALENT-1',
        name: 'Pentavalent-1 (DTP-HepB-Hib 1st Dose)',
        category: 'child',
        recommendedWeekOrAge: '6 Weeks',
        dueDate: '18 Sep 2026',
        status: 'overdue',
        notes: '⚠️ OVERDUE by 3 days! Essential primary immunization protecting against 5 life-threatening illnesses.',
      },
      {
        id: 'm2-opv1',
        code: 'OPV-1',
        name: 'Oral Polio Vaccine 1st Primary Dose',
        category: 'child',
        recommendedWeekOrAge: '6 Weeks',
        dueDate: '18 Sep 2026',
        status: 'overdue',
        notes: '⚠️ OVERDUE with Pentavalent-1. ASHA worker visit urgently required.',
      },
      {
        id: 'm2-penta2',
        code: 'PENTAVALENT-2',
        name: 'Pentavalent-2 (2nd Dose)',
        category: 'child',
        recommendedWeekOrAge: '10 Weeks',
        dueDate: '16 Oct 2026',
        status: 'upcoming',
      },
      {
        id: 'm2-penta3',
        code: 'PENTAVALENT-3',
        name: 'Pentavalent-3 (3rd Dose)',
        category: 'child',
        recommendedWeekOrAge: '14 Weeks',
        dueDate: '13 Nov 2026',
        status: 'upcoming',
      },
    ],
  },
  {
    id: 'mch-003',
    patientId: 'pat-rekha-meena',
    patientName: 'Rekha Meena',
    patientHealthId: 'RHC-2026-RM3390',
    patientPhone: '94601 22894',
    patientVillage: 'Govindpur',
    pregnancyStatus: 'PREGNANT',
    edd: '10 Feb 2027',
    lmp: '05 May 2026',
    gestationalWeeks: 14,
    isHighRisk: true,
    hrpIndicators: ['Severe Anaemia (Hb 7.8 g/dL)', 'Young Primigravida (Age 19)'],
    gravida: 1,
    para: 0,
    bloodGroup: 'B+',
    assignedVillage: 'Govindpur',
    assignedWorkerName: 'Meena Kumari (ASHA)',
    nextScheduledDate: '16 Sep 2026',
    nextScheduledMilestone: 'ANC-1 & TT-1 Administration',
    notes: 'Young pregnant mother. Missed registration appointment last week. High-risk severe anaemia.',
    milestones: [
      {
        id: 'm3-anc1',
        code: 'ANC-1',
        name: 'Antenatal Checkup 1 (Registration)',
        category: 'maternal',
        recommendedWeekOrAge: '12th week',
        dueDate: '16 Sep 2026',
        status: 'overdue',
        notes: '🚨 OVERDUE. Urgent home visit needed to evaluate Hb and schedule ultrasound.',
      },
      {
        id: 'm3-tt1',
        code: 'TT-1',
        name: 'Tetanus Toxoid 1 / Td-1',
        category: 'maternal',
        recommendedWeekOrAge: 'Early pregnancy',
        dueDate: '16 Sep 2026',
        status: 'overdue',
        notes: '🚨 OVERDUE. Administer immediately at next VHND.',
      },
      {
        id: 'm3-ifa1',
        code: 'IFA-1',
        name: 'IFA 1st Allotment (100 Tablets)',
        category: 'maternal',
        recommendedWeekOrAge: '14th week',
        dueDate: '16 Sep 2026',
        status: 'overdue',
        notes: '🚨 High risk: Severe anaemia. Must start therapeutic iron dose.',
      },
      {
        id: 'm3-anc2',
        code: 'ANC-2',
        name: 'Antenatal Checkup 2',
        category: 'maternal',
        recommendedWeekOrAge: '20th week',
        dueDate: '20 Oct 2026',
        status: 'upcoming',
      },
    ],
  },
  {
    id: 'mch-004',
    patientId: 'pat-kavita-ananya',
    patientName: 'Kavita Bai & Baby Ananya',
    patientHealthId: 'RHC-2026-KA4112',
    patientPhone: '95291 44801',
    patientVillage: 'Govindpur',
    pregnancyStatus: 'POSTPARTUM',
    childName: 'Baby Ananya',
    childDob: '10 Jun 2026',
    childGender: 'Female',
    childAgeWeeks: 14,
    isHighRisk: false,
    hrpIndicators: [],
    assignedVillage: 'Govindpur',
    assignedWorkerName: 'Meena Kumari (ASHA)',
    nextScheduledDate: '23 Sep 2026',
    nextScheduledMilestone: 'Pentavalent-3 + OPV-3 + fIPV-2',
    milestones: [
      {
        id: 'm4-bcg',
        code: 'BCG',
        name: 'BCG Vaccine',
        category: 'child',
        recommendedWeekOrAge: 'Birth',
        dueDate: '10 Jun 2026',
        completedDate: '11 Jun 2026',
        status: 'completed',
        administeredBy: 'PHC Staff',
      },
      {
        id: 'm4-penta1',
        code: 'PENTAVALENT-1',
        name: 'Pentavalent-1 & OPV-1',
        category: 'child',
        recommendedWeekOrAge: '6 Weeks',
        dueDate: '22 Jul 2026',
        completedDate: '23 Jul 2026',
        status: 'completed',
        administeredBy: 'ANM Saroj',
      },
      {
        id: 'm4-penta2',
        code: 'PENTAVALENT-2',
        name: 'Pentavalent-2 & OPV-2',
        category: 'child',
        recommendedWeekOrAge: '10 Weeks',
        dueDate: '19 Aug 2026',
        completedDate: '20 Aug 2026',
        status: 'completed',
        administeredBy: 'ANM Saroj',
      },
      {
        id: 'm4-penta3',
        code: 'PENTAVALENT-3',
        name: 'Pentavalent-3 & OPV-3 (Final Primary Dose)',
        category: 'child',
        recommendedWeekOrAge: '14 Weeks',
        dueDate: '23 Sep 2026',
        status: 'due',
        notes: 'Due this week on Wednesday Village Health Day.',
      },
      {
        id: 'm4-polio3',
        code: 'OPV-3',
        name: 'Oral Polio Vaccine Dose 3',
        category: 'child',
        recommendedWeekOrAge: '14 Weeks',
        dueDate: '23 Sep 2026',
        status: 'due',
        notes: 'Due this week together with Pentavalent-3.',
      },
    ],
  },
  {
    id: 'mch-005',
    patientId: 'pat-anita-gurjar',
    patientName: 'Anita Gurjar',
    patientHealthId: 'RHC-2026-AG7721',
    patientPhone: '96729 33491',
    patientVillage: 'Khetolai',
    pregnancyStatus: 'PREGNANT',
    edd: '02 Oct 2026',
    lmp: '26 Dec 2025',
    gestationalWeeks: 34,
    isHighRisk: true,
    hrpIndicators: ['Previous Caesarean Section', 'Gestational Diabetes'],
    gravida: 2,
    para: 1,
    bloodGroup: 'A+',
    assignedVillage: 'Khetolai',
    assignedWorkerName: 'Sunita Yadav (ASHA)',
    nextScheduledDate: '24 Sep 2026',
    nextScheduledMilestone: 'ANC Checkup 4 & Institutional Delivery Counseling',
    milestones: [
      {
        id: 'm5-anc1',
        code: 'ANC-1',
        name: 'Antenatal Checkup 1',
        category: 'maternal',
        recommendedWeekOrAge: '12th week',
        dueDate: '20 Feb 2026',
        completedDate: '20 Feb 2026',
        status: 'completed',
      },
      {
        id: 'm5-anc2',
        code: 'ANC-2',
        name: 'Antenatal Checkup 2',
        category: 'maternal',
        recommendedWeekOrAge: '20th week',
        dueDate: '15 May 2026',
        completedDate: '16 May 2026',
        status: 'completed',
      },
      {
        id: 'm5-anc3',
        code: 'ANC-3',
        name: 'Antenatal Checkup 3',
        category: 'maternal',
        recommendedWeekOrAge: '28th week',
        dueDate: '18 Jul 2026',
        completedDate: '18 Jul 2026',
        status: 'completed',
      },
      {
        id: 'm5-anc4',
        code: 'ANC-4',
        name: 'Antenatal Checkup 4 (High-Risk Delivery Planning)',
        category: 'maternal',
        recommendedWeekOrAge: '34th week',
        dueDate: '24 Sep 2026',
        status: 'due',
        notes: 'High-risk previous LSCS. Arrange transport to CHC Bikaner ahead of labor onset.',
      },
    ],
  },
];

export const MCH_DUE_ITEMS: MchDueAlertItem[] = [
  {
    id: 'mch-002-PENTAVALENT-1',
    recordId: 'mch-002',
    patientId: 'pat-sunita-aarav',
    patientName: 'Sunita Kumari',
    healthId: 'RHC-2026-SK8801',
    phone: '94142 88120',
    village: 'Govindpur',
    isHighRisk: true,
    hrpIndicators: ['Low Birth Weight (2.1 kg)'],
    category: 'child',
    milestoneCode: 'PENTAVALENT-1',
    milestoneName: 'Pentavalent-1 (DTP-HepB-Hib 1st Dose)',
    dueDate: '18 Sep 2026',
    status: 'overdue',
    daysOverdue: 3,
    pregnancyStatus: 'POSTPARTUM',
    childName: 'Baby Aarav',
    childAge: '6 weeks',
  },
  {
    id: 'mch-002-OPV-1',
    recordId: 'mch-002',
    patientId: 'pat-sunita-aarav',
    patientName: 'Sunita Kumari',
    healthId: 'RHC-2026-SK8801',
    phone: '94142 88120',
    village: 'Govindpur',
    isHighRisk: true,
    hrpIndicators: ['Low Birth Weight (2.1 kg)'],
    category: 'child',
    milestoneCode: 'OPV-1',
    milestoneName: 'Oral Polio Vaccine 1st Primary Dose',
    dueDate: '18 Sep 2026',
    status: 'overdue',
    daysOverdue: 3,
    pregnancyStatus: 'POSTPARTUM',
    childName: 'Baby Aarav',
    childAge: '6 weeks',
  },
  {
    id: 'mch-003-ANC-1',
    recordId: 'mch-003',
    patientId: 'pat-rekha-meena',
    patientName: 'Rekha Meena',
    healthId: 'RHC-2026-RM3390',
    phone: '94601 22894',
    village: 'Govindpur',
    isHighRisk: true,
    hrpIndicators: ['Severe Anaemia (Hb 7.8 g/dL)', 'Young Primigravida (Age 19)'],
    category: 'maternal',
    milestoneCode: 'ANC-1',
    milestoneName: 'Antenatal Checkup 1 (Registration)',
    dueDate: '16 Sep 2026',
    status: 'overdue',
    daysOverdue: 5,
    pregnancyStatus: 'PREGNANT',
    gestationalWeeks: 14,
  },
  {
    id: 'mch-001-ANC-3',
    recordId: 'mch-001',
    patientId: 'RHC-2026-8F4K92',
    patientName: 'Priya Devi',
    healthId: 'RHC-2026-8F4K92',
    phone: '94141 58392',
    village: 'Govindpur',
    isHighRisk: true,
    hrpIndicators: ['Severe Anaemia (Hb 8.6 g/dL)', 'Hypothyroidism'],
    category: 'maternal',
    milestoneCode: 'ANC-3',
    milestoneName: 'Antenatal Checkup 3 (28–34 Weeks)',
    dueDate: '22 Sep 2026',
    status: 'due',
    pregnancyStatus: 'PREGNANT',
    gestationalWeeks: 26,
  },
  {
    id: 'mch-001-IFA-2',
    recordId: 'mch-001',
    patientId: 'RHC-2026-8F4K92',
    patientName: 'Priya Devi',
    healthId: 'RHC-2026-8F4K92',
    phone: '94141 58392',
    village: 'Govindpur',
    isHighRisk: true,
    hrpIndicators: ['Severe Anaemia (Hb 8.6 g/dL)', 'Hypothyroidism'],
    category: 'maternal',
    milestoneCode: 'IFA-2',
    milestoneName: 'IFA 2nd Allotment (80 Tablets)',
    dueDate: '22 Sep 2026',
    status: 'due',
    pregnancyStatus: 'PREGNANT',
    gestationalWeeks: 26,
  },
  {
    id: 'mch-004-PENTAVALENT-3',
    recordId: 'mch-004',
    patientId: 'pat-kavita-ananya',
    patientName: 'Kavita Bai',
    healthId: 'RHC-2026-KA4112',
    phone: '95291 44801',
    village: 'Govindpur',
    isHighRisk: false,
    hrpIndicators: [],
    category: 'child',
    milestoneCode: 'PENTAVALENT-3',
    milestoneName: 'Pentavalent-3 & OPV-3',
    dueDate: '23 Sep 2026',
    status: 'due',
    pregnancyStatus: 'POSTPARTUM',
    childName: 'Baby Ananya',
    childAge: '14 weeks',
  },
  {
    id: 'mch-005-ANC-4',
    recordId: 'mch-005',
    patientId: 'pat-anita-gurjar',
    patientName: 'Anita Gurjar',
    healthId: 'RHC-2026-AG7721',
    phone: '96729 33491',
    village: 'Khetolai',
    isHighRisk: true,
    hrpIndicators: ['Previous Caesarean Section', 'Gestational Diabetes'],
    category: 'maternal',
    milestoneCode: 'ANC-4',
    milestoneName: 'Antenatal Checkup 4 (High-Risk Delivery Planning)',
    dueDate: '24 Sep 2026',
    status: 'due',
    pregnancyStatus: 'PREGNANT',
    gestationalWeeks: 34,
  },
];
